### PR TITLE
Add Math.fround test

### PR DESCRIPTION
**Pull request by topaxi**
See: https://developer.mozilla.org/en-US/docs/JavaScript/Reference/Global_Objects/Math/fround

### CODE REVIEW

**Comment by kangax** [comment]
@topaxi Thanks! I don't see `Math.fround` in the spec though.

@rwaldron @domenic Do you guys know of its status?

**Comment by rwaldron** [comment]
Yep, this is legit. It was temporarily known as Math.roundFloat32() (yuck!) but was changed to "fround" at the last meeting https://github.com/rwaldron/tc39-notes/blob/master/es6/2013-09/sept-17.md#55-mathroundfloat32

**Comment by kangax** [comment]
@rwaldron Thanks, Rick. Adding it then.

**Comment by rwaldron** [comment]
No problem! Anytime :)

**Pull request merged**
