### PR TITLE
Firefox 90 will ship Private Fields

### PR DESCRIPTION
**Pull request by afmenez**
Firefox 90 will enable Private Fields by default: https://spidermonkey.dev/blog/2021/05/03/private-fields-ship.html

### CODE REVIEW

**Review by ljharb — COMMENTED** [review]
I believe they also intend to ship `#x in obj`. Additionally, class fields are stage 4 now - they should be marked as ES2022.

**Comment by afmenez** [comment]
I can move the class fields to the ES2016+ tab, do you mean to do it on this PR?
Is there a test for this `#x in obj` yet?  I was not able to find it.

**Comment by nicolo-ribaudo** [comment]
It's the `Ergonomic brand checks for private fields` one

**Comment by ljharb** [comment]
Yes, it’d be great to move them here

**Comment by afmenez** [comment]
OK, I moved the class fields tests to the ES2016+ tab.
The Ergonomic Brand Checks are not passing yet on today's nightly, so I didn't change it.

**Review by ljharb — APPROVED** [review]

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
