### PR TITLE
update 6to5 to version 2.13.1

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Comment by sebmck** [comment]
See [here](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=true&code=bar%3B%0Alet%20bar%3B) for reference.

**Comment by kangax** [comment]
fwiw, I don't see anything in the fields when opening that link on iPhone 6

**Comment by kangax** [comment]
*fyi

**Comment by sebmck** [comment]
@kangax Odd, I'm getting a `Can't find variable: to5` in the REPL console on my iPhone 6.

Ping @thejameskyle

**Comment by kangax** [comment]
What is "optional transformer"?

**Comment by sebmck** [comment]
@kangax 6to5 has an [optional](http://6to5.org/docs/usage/transformers/#optional-transformers) [typeofSymbol](http://6to5.org/docs/usage/transformers/#typeof-symbol) transformer. It replaces all typeof unary expressions in a helper method that replicates native behaviour.

**Comment by kangax** [comment]
Gotcha. Thanks!

**Pull request merged**
