### PR TITLE
Adding Firefox 50

### PR DESCRIPTION
**Pull request by afmenez**
Adding Firefox 50.  Also updating Firefox 48 to stable on esnext-browsers.js.

### CODE REVIEW

**Comment by zloirock** [comment]
@afmenez can you rebase it?

**Comment by afmenez** [comment]
This was my first rebase here, and I couldn't find a "master" upstream.  So I did the rebase to upstream/gh-pages, is this correct?

**Comment by ljharb** [comment]
Yes, that's the main branch of the repo. However there's still a merge commit in your PR - do you need to force push still?

**Comment by afmenez** [comment]
I am not sure what you mean, I expected someone with the correct rights would merge my PR after I resolved the conflicts.  Do I need to do anything else?

**Comment by ljharb** [comment]
@afmenez right, i'm referring to https://github.com/kangax/compat-table/pull/860/commits/89a44c5d00b0cb6e3dc84c6d78e80ae33212e0f3 which is a merge commit - ideally you'd `git rebase` onto the latest gh-pages on this repo, and then `git push -f` which will cause the PR to be updated.

**Comment by afmenez** [comment]
That´s what I did, but without the "-f".  This PR was updated and now there are no conflicts with the base branch.  What I am missing?

**Comment by ljharb** [comment]
A rebase would remove the merge commit, and would require the -f. Are you using git merge, or git rebase?

**Comment by afmenez** [comment]
I am following this tutorial:
https://help.github.com/articles/syncing-a-fork/

It says to use git merge.  I just changed upstream/master for upstream/gh-pages

**Comment by afmenez** [comment]
OK, I had to solve another conflict.  This time I used rebase instead of merge, and had to do a push -f as suggested by @ljharb .

**Pull request merged**
