### PR TITLE
Mark Edge 15 as stable, update its data

### PR DESCRIPTION
**Pull request by mgol**
Data updated for EdgeHTML 15.15063, i.e. the version included in the
Windows 10 Creators Update (Version 1703, OS Build 15063.138).

### CODE REVIEW

**Review by afmenez — APPROVED** [review]
LGTM

**Review by chicoxyzzy — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
Thank you!

**Comment by klimashkin** [comment]
https://github.com/kangax/compat-table/issues/1076

**Comment by martinsuchan** [comment]
Edge 15 also supports Shared Memory & Atomics behind flag. The table does not reflect it yet:
https://blogs.windows.com/msedgedev/2017/04/20/improved-javascript-performance-webassembly-shared-memory/

**Comment by chicoxyzzy** [comment]
@martinsuchan do you want to contribute? :)

**Pull request merged**
