### PR TITLE
Typescript 5.5 released

### PR DESCRIPTION
**Pull request by afmenez**
Ditto.

### CODE REVIEW

**Review by chicoxyzzy — APPROVED** [review]

**Review by chicoxyzzy — COMMENTED** [review]
It also supports Set methods as far as I remember.

Note: I see that Set methods are shown as Stage 2 proposal, which is not true, as it's stage 4 (we can add it to ES2025), but we can fix that in another PR

**Review by ljharb — APPROVED** [review]
followup PRs are welcome

**Comment by ljharb** [comment]
Filed #1897 for some stage changes.

**Comment by afmenez** [comment]
Yes, it is on the release notes for 5.5:
"TypeScript 5.5 declares [new proposed methods for the ECMAScript Set type](https://github.com/tc39/proposal-set-methods).

Some of these methods, like union, intersection, difference, and symmetricDifference, take another Set and return a new Set as the result. The other methods, isSubsetOf, isSupersetOf, and isDisjointFrom, take another Set and return a boolean. None of these methods mutate the original Sets."

But I was unable to complete the tests on my machine, so I didn't update the results.  I did it for Chrome(#1895) and Firefox(#1898).

**Pull request merged**
