### PR TITLE
String.prototype.matchAll fixed on Firefox 73

### PR DESCRIPTION
**Pull request by afmenez**
String.prototype.matchAll now throws on non-global regEx.

### CODE REVIEW

**Review by zloirock — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
The first two commits in this PR are not related to `String.prototype.matchAll`

**Comment by afmenez** [comment]
Yep, and they are not even mine.  Don't know how they appeared here.

**Comment by zloirock** [comment]
Seems @ljharb forced pushed to `gh-pages` :-D

**Comment by ljharb** [comment]
indeed; those commits shouldn't be on master.

**Comment by zloirock** [comment]
They should be.

**Pull request merged**
