### PR TITLE
Update "flagged" results for released Edge 15

### PR DESCRIPTION
**Pull request by afmenez**
I have tested the Edge 15 with the "experimental JS features" flag enabled.  There are some extra features implemented, but surprisingly there are 2 regressions on SIMD.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
> surprisingly there are 2 regressions on SIMD

According to [this](https://github.com/tc39/ecmascript_simd/),
> SIMD.js has been taken out of active development in TC39 and removed from Stage 3, and is not being pursued by web browsers for implementation.

**Comment by ljharb** [comment]
None the less, regressions are surprising.

**Comment by afmenez** [comment]
Sad to know.  Does this mean it has regressed to stage 2, stage 0, or was dropped completely?  We may have to relocate the tests, but it doesn't mean the results are invalid.

Also, there are a lot of other updates on this PR besides the SIMD ones.

**Review by chicoxyzzy — COMMENTED** [review]
I'm OK with merging this for now and tracking SIMD issues in https://github.com/kangax/compat-table/issues/1103 and https://github.com/tc39/proposals/issues/46

**Review by ljharb — APPROVED** [review]

**Pull request merged**
