### PR TITLE
update test results for 'Edge 15.15014

### PR DESCRIPTION
**Pull request by dnalborczyk**
update test results for: Edge 39.15014.1000.0/EdgeHTML 15.15014
on Windows 10 Version 1607 Build 15014.1000

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
@Chudesnov @MaxJaison can you guys check this?

**Comment by chicoxyzzy** [comment]
I'm still didn't find a way to install that version of Edge. VM images on official website include old versions

**Comment by Chudesnov** [comment]
@chicoxyzzy Edge VM images are usually updated less often than the corresponding 
Insider Preview builds. You can create a VM image manually using an ISO from [Windows Insider website](https://www.microsoft.com/en-us/software-download/windowsinsiderpreviewadvanced).

**Comment by afmenez** [comment]
The final version is finally available, and I can confirm the ES6 and ES2016+ changes, but the esnext changes (SIMD) are not enabled by default.  This patch needs an update.

**Review by chicoxyzzy — CHANGES_REQUESTED** [review]
@dnalborczyk could you please update your PR?

**Comment by mgol** [comment]
@dnalborczyk ping. If you don't have time I can submit a more up-to-date PR tomorrow for the build 15.15063 (i.e. Creators Update final).

**Comment by afmenez** [comment]
Tomorrow is the expected release of Windows 10 Creators Update, which contains Edge 15.  You could also update Edge 15 status on your patch.

**Comment by mgol** [comment]
Yep, I've already installed the update.

**Comment by mgol** [comment]
I submitted #1074 with the current data from the stable Edge 15.

**Comment by afmenez** [comment]
Since #1074 was merged, I believe this can now be closed as redundant.

**Comment by chicoxyzzy** [comment]
We decided to merge #1074

**Pull request closed without merging**
