### PR TITLE
Array.prototype.{flatten, flatMap} and Numeric Separators moved to Stage 3

### PR DESCRIPTION
**Pull request by afmenez**
Moving the tests and updating results for old Forefox and Opera versions.

### CODE REVIEW

**Comment by afmenez** [comment]
This does the same changes as #1228 and #1229, but in a single push to avoid the merge conflicts.  It also adds some results too.

**Comment by afmenez** [comment]
@chicoxyzzy: I did this patch without knowing about the other ones.  Sorry for the duplication.

**Review by ljharb — APPROVED** [review]
LGTM

**Comment by afmenez** [comment]
Tks!

**Comment by chicoxyzzy** [comment]
@afmenez that's ok but please check if PR already exists to be sure we don't do extra work and don't create extra noise in notifications

**Pull request merged**
