### PR TITLE
Non-standard Generators (JS 1.8) dropped from Firefox 58

### PR DESCRIPTION
**Pull request by afmenez**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1083482
This was actually tested with yesterday's nightly build.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
🎉

**Comment by jandem** [comment]
Thank you! Note that we also removed Function.prototype.isGenerator in Firefox 58 - maybe you could fix that one too while you're here? :) https://bugzilla.mozilla.org/show_bug.cgi?id=1119777

**Comment by afmenez** [comment]
Done.  Any news on "Generator comprehensions (ES draft style)", so that we can make this patch complete? :)

**Comment by jandem** [comment]
> Done. Any news on "Generator comprehensions (ES draft style)", so that we can make this patch complete? :)

That's https://bugzilla.mozilla.org/show_bug.cgi?id=1414340 - nobody is working on it yet, hopefully soon.

**Comment by jandem** [comment]
> That's https://bugzilla.mozilla.org/show_bug.cgi?id=1414340 - nobody is working on it yet, hopefully soon.

Heads up: I just landed patches for this (removing ES draft array/generator comprehensions). Should be in tomorrow's Nightly, hopefully.

**Comment by afmenez** [comment]
I just submitted #1218 to update this. Great progress on removal of non-standard features!

**Comment by afmenez** [comment]
This was Firefox 59 nightly actually, I will fix it with the 57 release patch.

**Comment by jandem** [comment]
> This was Firefox 59 nightly actually, I will fix it with the 57 release patch.

No this was 58. Nightly is 59 now but the merge happened after these patches landed. Either that or our release tracking in bugzilla is broken :)

**Comment by afmenez** [comment]
That's what I thought at first, but I am now running Firefox 58b1 and it is passing the test...

**Pull request merged**
