### PR TITLE
Adding tests for updated identifier syntax

### PR DESCRIPTION
**Pull request by afmenez**
This one addresses #1026.
I don't know how to name the new tests, so I just used the declaration tested.  i am open to better ideas.
Also, I have only tested with the browsers/versions listed in patch.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Probably we could use `null` values (will be rendered as gray cell with ? sign) for untested browsers / environments

**Comment by ljharb** [comment]
I would definitely prefer explicit values of `true` (tested, passes), `false` (tested, fails), `null`/`undefined` (untested).

**Comment by afmenez** [comment]
I agree and will do, but shouldn't null be the default instead of false then?

**Comment by ljharb** [comment]
Yes, it should. I'd changed that at one point but got pushback; i'm not sure why.

**Comment by afmenez** [comment]
Opened issue #1123 about that.

**Comment by afmenez** [comment]
Done adding null to untested browsers/transpilers/engines.  It was a lot of work to get it right, and if this is going to be enforced in the future we need to fix #1123 fast.

**Review by chicoxyzzy — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
@afmenez sorry for conflicts after merging previous PRs. This one looks good to me

**Comment by afmenez** [comment]
Done rebasing.  Please prioritize merging this PR over my later ones.

**Review by ljharb — APPROVED** [review]

**Pull request merged**
