### PR TITLE
Safari TP 52 release

### PR DESCRIPTION
**Pull request by chicoxyzzy**
flatten and flatMap are enabled by default since TP 51

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Seems fine, but "flatten" isn't going to be the name anymore, so I'm not sure if it's worth adding this.

**Comment by chicoxyzzy** [comment]
@ljharb sure, but our tests still use 'flatten' and 'flatMap' as method names. Did TC39 reach consensus on new names?

**Comment by ljharb** [comment]
Not yet.

**Comment by chicoxyzzy** [comment]
@ljharb what do you think about last commit? Is wording correct? I think this note makes all results in `Array#flatten` row more clear

**Comment by ljharb** [comment]
Looks good, altho it’s only flatten that is going to change.

**Pull request merged**
