### PR TITLE
Implement the "Uint8Array to/from base64 and hex" tests

### PR DESCRIPTION
**Pull request by afmenez**
I am not sure about the 'significance' field.

### CODE REVIEW

**Comment by ljharb** [comment]
The tests from https://github.com/es-shims/es-arraybuffer-base64/tree/main/test could help make these more thorough.

(There's also 6 methods, and you've only got 4 methods added here)

**Comment by afmenez** [comment]
I have added the 2 missing tests, but I don't believe the tests here need to be so complete... are we going for conformance tests or basic functionality tests?

**Comment by ljharb** [comment]
They definitely don't need to be fully complete - more like, find some of the edge cases, and exercise all of the options.

**Review by chicoxyzzy — APPROVED** [review]

**Review by ljharb — APPROVED** [review]
I'd still like to see tests that exercise some of the options but this is a great start :-)

**Pull request merged**
