### PR TITLE
Updating ESnext results for Firefox 53

### PR DESCRIPTION
**Pull request by afmenez**
Updating ESnext results for Firefox 53 (21/dec Nigthly).  New feature, no surprises.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
We do need to add subtests here tho, to ensure global is nonenumerable.

**Review by chicoxyzzy — APPROVED** [review]
LGTM

**Comment by chicoxyzzy** [comment]
oops @ljharb din't noticed your comment. can we add this test in another PR?

current test passes for me

**Comment by chicoxyzzy** [comment]
also I checked it's non-enumerable

**Comment by ljharb** [comment]
In ff yes; not in node

**Comment by ljharb** [comment]
Another PR is fine ofc

**Comment by chicoxyzzy** [comment]
@afmenez do you want to add a test?

**Comment by afmenez** [comment]
Sorry, I have no idea how to do this.  :(

**Comment by chicoxyzzy** [comment]
I believe test should be

```js
typeof global === 'object' && 'global' in global && !global.propertyIsEnumerable('global');
```

I'll add PR myself later if nobody will do it before :)

**Comment by ljharb** [comment]
`Object.prototype.propertyIsEnumerable.call(global, 'global')` would be safer, but otherwise good.

I'd prefer to do it in a separate subtest, not a full test, so that node can pass "has global as the global object", but fail "nonenumerable".

**Comment by chicoxyzzy** [comment]
Shouldn't `typeof global === 'object'` be added anyway to prevent `ReferenceError` when there is no `global`?

**Comment by chicoxyzzy** [comment]
also `Object.prototype.propertyIsEnumerable.call(global, 'global')` will return `false` if there is no `global` in `global` object. This is not safe IMO

**Comment by ljharb** [comment]
@chicoxyzzy it's safe after you've done `'global' in global` - i was just saying, not to call `propertyIsEnumerable` directly on the object.

**Comment by ljharb** [comment]
So actually, the test should be getting the actual global with `Function('return this')()`, and checking that.

**Comment by ljharb** [comment]
I can write a PR for it ¯\\\_(ツ)_/¯

**Comment by ljharb** [comment]
Submitted #991.

**Pull request merged**
