### PR TITLE
[ESNext] Add `compositeKey` and `compositeSymbol`

### PR DESCRIPTION
**Pull request by zloirock**
(they should live on built-in modules, but they are still unavailable)

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
I think this one is too premature to add - the repo itself hasn’t even been submitted by the champion to the proposals list, and until builtin modules progresses (if it does), it’d have to supply a global name to access it (which is what these tests would have to use).

**Comment by zloirock** [comment]
@ljharb it's a part of richer keys stage 1 proposal. It's on the list. This proposal contains 2 separate parts, this PR adds the first. For preventing confusion, I can rename this test case by the name of the main proposal.

**Comment by ljharb** [comment]
The proposal doesn’t yet provide enough information to implement it or test for it. This is not uncommon for proposals that agent stage 3.

**Comment by zloirock** [comment]
@ljharb I do not completely understand you. For me, in the repo - readme and polyfill - enough information for basic tests. Missed parts were discussed with the champion when I wrote a polyfill.

**Comment by ljharb** [comment]
The champion needs to submit the repo in a PR to the proposals list; and if it’s goijg to (foolishly, imo) chain itself to builtin modules, then it’s not possible for anything to pass any tests for it until builtin modules exist.

I completely agree that it’s possible to implement a polyfill for the individual functions, and tests for those, but i don’t agree that the proposal provided enough information to test the proposal overall (which is what goes in this table).

**Comment by zloirock** [comment]
@ljharb 
> The champion needs to submit the repo in a PR to the proposals list;

This proposal already in the list and was presented tc39, seems just the link to the repo should be updated:

image

> foolishly, imo

I think the same, [see the issue](https://github.com/bmeck/proposal-richer-keys/issues/1).

> but i don’t agree that the proposal provided enough information to test the proposal overall 

Both parts of the proposal - keys composition and rekey - clearer than a serious part of the rest proposals in the ESNext table, so it's a strange argument

**Comment by zloirock** [comment]
сс @bmeck

**Comment by bmeck** [comment]
@ljharb I do plan on requesting stage 2 in January, perhaps it would be best to wait until after then? The proposal is split into 2 parts but is being pushed in tandem rather than disparate proposals due to overlap of context.

**Comment by ljharb** [comment]
Given https://github.com/bmeck/proposal-richer-keys/issues/1#issuecomment-450198871, i don’t think the table should have a test for compositeKey at all at this time.

**Comment by bmeck** [comment]
@ljharb I disagree with that statement, locations of references are free to change and do so during stage advancement.

**Comment by ljharb** [comment]
That is true - but at the moment, there exists no location. Typically they change from one exiting location to a different one, and the test changes along with them.

The table doesn’t have tests for unobservable things, and at the moment, compositeKey is impossible to observe or access.

**Comment by bmeck** [comment]
@ljharb that just seems to imply that the tests could be amended to allow for such access to be injected rather than preventing any testing. I don't see how that blocks things.

**Review by chicoxyzzy — APPROVED** [review]
LGTM

**Comment by zloirock** [comment]
@ljharb you still wanna block it?

**Comment by ljharb** [comment]
@zloirock based on today's TC39, rekey and compositeKey are being split out; i think compositeKey can't possibly have any tests unless the proposal specifies an existing way for it to be reachable: either via syntax, or via global API.

**Pull request closed without merging**
