### PR TITLE
Adding duktape versions, results

### PR DESCRIPTION
**Pull request by afmenez**
Adding obsolete versions 1.0...1.8 and unstable version 2.2.
Adding some results for the new versions (based on release notes).

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
cc @svaarala

**Comment by svaarala** [comment]
Awesome :)

**Review by chicoxyzzy — APPROVED** [review]

**Comment by afmenez** [comment]
Rebased to resolve conflicts.

**Comment by chicoxyzzy** [comment]
thank you!

**Comment by afmenez** [comment]
I'd like to reinforce that all the data on the patch came from the duktape site, I have not run any tests.  It would be nice if someone more knowledgeable could:
- Check/add the retire dates for all versions.  I added the ones that I could deduce, but they may be worng;
- Check the test results.  I added the results from the release notes, but I don't know if the tests can actually run.  Also, I found no info for the ES5, International and non-standard tabs;

**Comment by svaarala** [comment]
The data for 2.0 and 2.1 are from actual test runs, and I'll update the 2.2 results from an actual test run too when that release happens. I think you should be able to run tests for 1.x too, using the same test runner as I've used for 2.0 and 2.1 (it's now committed to compat-table).

**Pull request merged**
