### PR TITLE
 Added 3 more destructuring tests

### LINKED ISSUE #322: Destructuring in for-of heads
Just a note that a test for these ought be added.

```
result = "";
for (var [x, y] of [[1,2],[3,4]]) {
  result += '' + x + y
}
return result === "1234";
```

### PR DESCRIPTION
**Pull request by webbedspace**
Added tests for for-in heads, for-of heads, and multiples in one var statement (replacing the footnote for the WebKit browsers). Closes #322.

### CODE REVIEW

**Comment by kangax** [comment]
What is "es6/es6.html" for?

**Comment by webbedspace** [comment]
That was included by mistake - I made a copy of the index.html and modified the master.js/master.css file URL to be absolute-pathed so that I could upload the ES6 tests to a server of mine and then test them in a (Windows 10 preview) VM that has easy web access but difficult local file access. Let me just... amend that.

**Comment by kangax** [comment]
Alrighty, merging :)

**Comment by webbedspace** [comment]
That rebase accidentally reverted one of the recent fixes (forgot to git pull on that particular computer, gah), so I committed a quick re-do just now. Hope that's alright.

**Comment by kangax** [comment]
Sure, no problem.

**Pull request merged**
