### PR TITLE
Add "use strict" to class tests that are unrelated to strict mode

### PR DESCRIPTION
**Pull request by arv**
For example it makes no sense to fail "Array is subclassable" just.
because V8 does not allow class syntax in sloppy mode.

### CODE REVIEW

**Comment by arv** [comment]
@kangax What do you think? Also, I guess I should update the browser results?

**Comment by ljharb** [comment]
I think we might need separate tests, one for strict and one for sloppy.

Chrome absolutely should fail some test if it doesn't work in sloppy mode. Sloppy code isn't going away any time soon :-)

**Comment by arv** [comment]
I kept all the top level class tests as is (sloppy).

But the question if super.prop works as expected inside an arrow function is irrelevant to sloppy mode.

**Comment by ljharb** [comment]
That's quite true. But since an engine exists where the mode affects how it works, it should probably be tested in both modes. If V8 doesn't support something in sloppy mode that the spec says it should, something should fail. It's not something that should be acceptable, or glossed over, that a feature doesn't work by default (since sloppy is default outside of `class` and modules).

**Comment by webbedspace** [comment]
The solution I've now implemented for this is to add a "Strict" result value, which is regarded for percent calculations as equivalent to "Flag" - as discussed previously in #498. (This will also report "strict-only" results in browser tests, which finally allows features with this restriction to be tracked more easily.)

**Comment by paulirish** [comment]
Commit of @webbedspace's solution here: https://github.com/kangax/compat-table/commit/91c2aab8648800c81d0927d71ce4be5052b57d5a

screenshot: 
image

While I agree we can't treat a pass in strict as 100% support, I'm happy the table now communicates the feature is available to devs if they go for strict.  

I think it's probably worth scoring as partial credit instead of 0%... I've opened that as a new issue: #575

**Comment by arv** [comment]
Thanks. Having the tests run in both strict and sloppy seems like the right thing to do.

**Pull request closed without merging**
