### PR TITLE
add xs6

### PR DESCRIPTION
**Pull request by mkellner**
Add Kinoma's xs6 engine

### CODE REVIEW

**Comment by ljharb** [comment]
@mkellner can you document how you obtained these results?

**Comment by zloirock** [comment]
Please, rebuild the table.

**Comment by ljharb** [comment]
Also "xs6" isn't very googleable - could you make the "full" name include "kinoma"?

**Comment by mkellner** [comment]
This document describes how we obtained the results:
http://kinoma.com/develop/documentation/js6/

It includes instructions on how to run the tests after building the KinomaJS tree.

**Comment by ljharb** [comment]
(To rebuild the table, run `npm install && npm run build` in the repo)

**Comment by zloirock** [comment]
@mkellner did you saw [the result](http://kinoma.github.io/compat-table/es6/)? Please, [increase colspan for engines](https://github.com/kangax/compat-table/blob/gh-pages/es6/skeleton.html#L118) and set the column, for example, near `Echo JS`.

**Comment by mkellner** [comment]
I opened the table locally in my browser and I now see XS6 next to EchoJS in the Servers/runtimes category, so I think we're good to go.

**Comment by kangax** [comment]
LGTM. Out of curiosity, what are the reasons for not implementing the rest 3% of the features?

**Comment by mkellner** [comment]
I think we'll get there eventually. This engine is used in commercial IOT products, phone apps and supports the rest of our KinomaJS stack. This article describes a bit of the philosophy about why we decided to go with ECMAScript for our products: http://blog.kinoma.com/2015/06/language-matters/

**Comment by mkellner** [comment]
Please let me know if you need me to do anything else here.

**Pull request merged**
