### PR TITLE
Updating test results for Opera 10.5 ... Opera 12.1

### PR DESCRIPTION
**Pull request by afmenez**
Now that #1210 was merged, I was able to test and update the results for Opera 10.5 to opera 12.1. Opera 10 and earlier still won't run.

What is in this patch:
- Fixed wrong results for all the tables;
- Added explicit `false` where the tests fail;
- Enabling Opera 12.1 (the last version with own engine), hidden by default, on all tables;

Notice that because of issue #1118, some results will not show on the rendered tables, especially on es2016+ and esnext.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by afmenez** [comment]
```
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! compat-table@0.0.0 lint: `jshint .`
npm ERR! Exit status 2
npm ERR! 
npm ERR! Failed at the compat-table@0.0.0 lint script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm ERR! A complete log of this run can be found in:
npm ERR!     /home/travis/.npm/_logs/2017-10-26T18_36_00_400Z-debug.log
```
Any idea how to fix this?

**Comment by ljharb** [comment]
travis shows this:
```sh
> jshint .
data-es6.js: line 3220, col 19, Duplicate key 'opera10_50'.
data-non-standard.js: line 537, col 15, Duplicate key 'opera10_50'.
```

**Comment by afmenez** [comment]
Ooops, my bad.  Is there a way to run this tests before opening the PR?

**Comment by ljharb** [comment]
@afmenez `npm install && npm test`, locally, should do it (in any node project)

**Review by ljharb — APPROVED** [review]

**Comment by afmenez** [comment]
Great, I'll add this step to my merge preocedure.  It should be on the README.md too!

**Comment by ljharb** [comment]
While it’s an expected step for every repo with a package.json, more documentation never hurts :-)

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
