### PR TITLE
ECMAScript 402 Internationalization compat-table

### LINKED ISSUE #358: ES I18n API
Inspired by https://whereswalden.com/2014/12/11/introducing-the-javascript-internationalization-api/ — and considering that Chrome has some support for that as well — I'm thinking perhaps we can include it somewhere in compat tables (non standard? es7? another table?)

### PR DESCRIPTION
**Pull request by keithamus**
Based on the discussion in #358 - this is the preliminary work to get a compat-table for the [ECMA-402 ECMAScript Internationalization API Specification](http://www.ecma-international.org/ecma-402/1.0/).

This features a new table, which appears next to the ES7 compat-table link - like so:
screen shot 2014-12-16 at 13 10 50.

Here is the todo list for what needs doing to complete this PR:
- [x] Create separate Intl compat table
- [x] Link other table's HTML skeletons to the Intl table
- [x] Add base set of tests for Intl object
- [x] Add base set of tests for Intl.Collator object
- [ ] Add full set of tests for Intl.Collator object (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/intl402))
- [x] Add base set of tests for Intl.NumberFormat object
- [ ] Add full set of tests for Intl.NumberFormat object (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/intl402))
- [x] Add base set of tests for Intl.DateTimeFormat object
- [ ] Add full set of tests for Intl.DateTimeFormat object (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/intl402))
- [x] Add base set of tests for Date#toLocaleString() 
- [ ] Add full set of tests for Date#toLocaleString() (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/built-ins/Date/prototype/toLocaleString)
- [x] Add base set of tests for Date#toLocaleDateString()
- [ ] Add full set of tests for Date#toLocaleDateString() (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/built-ins/Date/prototype/toLocaleDateString)
- [x] Add base set of tests for Date#toLocaleTimeString()
- [ ] Add full set of tests for Date#toLocaleTimeString() (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/built-ins/Date/prototype/toLocaleTimeString)
- [x] Add base set of tests for Number#toLocaleString()
- [ ] Add full set of tests for Number#toLocaleString() (there is no test262 suite for this - maybe we should PR a set before porting them to compat-table?)
- [x] Add base set of tests for String#localeCompare()
- [ ] Add full set of tests for String#localeCompare() (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/built-ins/String/prototype/localeCompare)
- [x] Add base set of tests for Array#toLocaleString()
- [ ] Add full set of tests for Array#toLocaleString() (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/built-ins/Array/prototype/toLocaleString)
- [x] Add base set of tests for Object#toLocaleString()
- [ ] Add full set of tests for Object#toLocaleString() (mimicking [test262 test suite](https://github.com/tc39/test262/tree/83b07ff15eadb141c3d6f4d236a8733b720041d2/test/built-ins/Object/prototype/toLocaleString)
- [ ] Run tests in browsers, apply results to test suite

I'll regularly push up to this branch - and commit the results of the build task each time so it is visible at http://keithamus.github.io/compat-table/esintl/ for review.

Comments welcome on what already exists.

(Fixes #358)

### CODE REVIEW

**Comment by kangax** [comment]
@keithamus I think we can actually push this out, with basic support. Just need to fill in some results, which I can certainly help with. For example, my Chrome 41 is fully green. So if FF38. Safari 8 (and latest nightly) is green on bottom 7 tests.

**Comment by kangax** [comment]
Firefox is fully green since 29

**Comment by kangax** [comment]
Just realized that last 7 rows are all the old things (at least basic checks) since at least ES3.

**Comment by keithamus** [comment]
Yeah I agree - I'll get some commits to wrap up basic support, then extend with later PRs.

The prototype methods (the last 7 rows you mention) exist in older ES specs, but did not have Intl support - this is where Intl tests need to go more in depth to find out what is supported.

**Comment by kangax** [comment]
@rwaldron just wanted to ping you about this to let you know about any development here (now that you're taking care of it, right?)

**Comment by keithamus** [comment]
Sorry about not updating this PR in a while. If you'd like I can spend some time on just getting the basic parts in tonight?

**Comment by kangax** [comment]
@keithamus No pressure! But if you can get something basic rolling — of course that would be better than nothing :)

**Comment by keithamus** [comment]
Alright. I've updated the suite, added some tests (still not enough to cover all tests), and I've gone through and added results for all browsers & engines where I could. I'd say this is ready to merge to demonstrate **basic** support in browsers, but like ES6/7 there are is much more nuance we'll need to display - but this is a good starting point.

You can see the results over at http://keithamus.github.io/compat-table/esintl/. Other build files have been touched because the es-intl link needed to be added to the other pages. Let me know if you've got any changes, but otherwise this is good to merge IMO.

**Comment by keithamus** [comment]
Also @kangax if you merge this one, I'll file an issue about getting the rest of the tests in place to have a full Intl test suite. If I make PRs I'll probably do them one at a time though, so as not to stall the progress on this :smile:

**Comment by rwaldron** [comment]
@kangax thanks. 

The most important stuff in Ecma-402, 2nd Edition will be spec alignment and almost no changes on the surface. One thing you'll want to start testing is `Array.prototype.toLocaleString`, which is the only real addition

**Comment by keithamus** [comment]
@rwaldron I obviously have no place to question you, but I thought ES6 locale functions started taking Intl objects as arguments, which wasn't part of ES5. Is that not the case?

**Comment by keithamus** [comment]
Hey @kangax I've rebased this branch. Keen to see it get merged. I can extend the tests in a new PR

**Comment by kangax** [comment]
Thanks @keithamus

**Comment by keithamus** [comment]
:tada:

**Comment by jedwards1211** [comment]
Sorry to bother you guys, but do you know if `core-js` or any other common polyfills out there support the `locales` and `options` arguments to `Date.prototype.toLocaleString`?  I'm having trouble finding any evidence that they do.

**Pull request merged**
