### PR TITLE
Rename old compilers shortcuts for consistency with #1400

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Do we not have typescript targets that don't include core-js?

**Comment by zloirock** [comment]
@ljharb the builder generates tests for it (and for `babel`), but we haven't it in the table.

**Comment by ljharb** [comment]
We should probably add them.

**Comment by zloirock** [comment]
I'm not sure about it. We have already too many columns for compilers. Features which require `core-js` have notes about it.

**Comment by ljharb** [comment]
Perhaps a redesign where things like babel, core-js, etc, can be toggled on or off on top of the basic runtime-less list?

Fair tho that as long as all the things that require the runtime have a note, it's fine - mainly thinking that we should find a way to have a single column for babel 6, and one for 7, and be able to pick a core-js version to apply on top of both (or none)

**Comment by zloirock** [comment]
Makes sense.

**Comment by kangax** [comment]
Relatedly, sometimes I open compat table to find certain feature but don't remember part of which "year" it is. It'd be nice to redesign it in such a way that it was searchable without toggling ES revisions.

**Pull request merged**
