### PR TITLE
 Firefox 57 released

### PR DESCRIPTION
**Pull request by afmenez**
Well, not officially until tomorrow but the installers are already available on the ftp servers.

This patch updates version tags, adds version 59 and retires ancient versions.

It also fixes the version of two of my recent pushes, which were merged with 58 but are actually 59.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by jandem** [comment]
The Nightly 58 changes were correct, I just checked with the 58 beta 3 build: http://ftp.mozilla.org/pub/firefox/releases/58.0b3/

**Comment by afmenez** [comment]
Hum, I am now running Firefox 58b1 and it is passing both tests... were both removals backported to b2/b3?

**Comment by jandem** [comment]
> Hum, I am now running Firefox 58b1 and it is passing both tests... were both removals backported to b2/b3?

I think there was an early merge last week for beta 58. Then I landed the array/generator comprehension removal patches and they were merged to beta this week, so they're in beta 3. Sorry for the confusion!

**Comment by afmenez** [comment]
OK, I'll try to download the 58b3 later today, re-run the tests and update this patch.

**Review by chicoxyzzy — CHANGES_REQUESTED** [review]
58b3 updates

**Comment by afmenez** [comment]
Done updating FF58beta results.  Changes in the es2016+ tab are due to #1164.

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
