### PR TITLE
Adds Safari 7.1 and Safari 8

### PR DESCRIPTION
**Pull request by dentuzhik**
29 new features in ES6.
"error stack" in non-standard.

### CODE REVIEW

**Comment by kangax** [comment]
Could you update to include Safari 8 as well? It seems completely identical to 7.1 on my Yosemite (39 features on ES6).

**Comment by dentuzhik** [comment]
Unfortunately, I can't currently test on Yosemite. I could give you a push access to my fork. If they are both identical it's the matter of search/replace and editing browser labels.

Or it just could be done separately, after merging this pr.

**Comment by kangax** [comment]
I'm saying I'd like to combine 7.1 and 8 right away, since it's identical. Thought it'd be more convenient to just amend this PR, no?

**Comment by dentuzhik** [comment]
Non-standard and ES7 features are also identical?

**Comment by kangax** [comment]
Is it 10/41 on non-standard in 7.1? ES7 — I'm sure it's the same; WebKit hasn't gotten to any of that stuff yet, even in nightlies.

**Comment by dentuzhik** [comment]
Yep it's 10/41. I'll change commit to include both.

**Comment by kangax** [comment]
Awesome, thanks!

**Comment by dentuzhik** [comment]
Done!

**Comment by kangax** [comment]
Perfect, thanks!

**Pull request merged**
