### PR TITLE
Mark Node 4 as obsolete

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
I don’t agree that it’s obsolete just because it’s out of LTS.

**Comment by chicoxyzzy** [comment]
@ljharb its end of life is 2018-04-30

https://github.com/nodejs/Release

**Comment by chicoxyzzy** [comment]
https://twitter.com/nodejs/status/987299954174693376

**Comment by ljharb** [comment]
Yes, but obsolescence is not determined solely or even primarily by official vendor support.

**Comment by afmenez** [comment]
This discussion comes back from time to time, and the conclusion is always different.  I do believe that it IS obsolete when it gets out of LTS, and that's what the tag obsolete=true is for.  I do not believe that the results should be removed from the table while there is significant use of this version, and that would be obselete="very".

**Review by afmenez — APPROVED** [review]
LGTM

**Comment by chicoxyzzy** [comment]
@ljharb now it's time I think

**Comment by chicoxyzzy** [comment]
ping @ljharb

**Review by ljharb — APPROVED** [review]

**Pull request merged**
