### PR TITLE
Chrome 45 has been released

### PR DESCRIPTION
**Pull request by mgol**

### CODE REVIEW

**Comment by webbedspace** [comment]
🚨You didn't update the colspan in `skeleton.html`🚨

**Comment by mgol** [comment]
colspan of which column? What does display incorrectly? I didn't add/remove any browser here.

**Comment by webbedspace** [comment]
Actually, you sorta did - `obsolete` browsers aren't visible by default. Take a look at the current page and see where e.g. the mobile column is now.

(This wouldn't be a problem if this thing automatically computed the colspans at build time, like a useful piece of software.)

**Comment by mgol** [comment]
> Actually, you sorta did - obsolete browsers aren't visible by default.

They're not visible but they're there, that doesn't affect `colspan`.

What's broken according to you? I've been clicking various checkboxes and the table looks fine in all cases.

**Comment by webbedspace** [comment]
> They're not visible but they're there, that doesn't affect `colspan`.

It does, though? All of the cells in the obsolete browser columns have `display:none`, so that entire column is essentially gone, and the top cell is spanning over a column that isn't there anymore, and thus it's 1 greater than what it should be.

Just look at this when you load the page initially:

So you know, the `colspan` is dynamically recalculated and fixed by the JS whenever you adjust a checkbox, so the problem disappears as soon as that action is performed.

**Comment by mgol** [comment]
You're right, d'oh. So it's wrong only on initial load as that's when it's not getting re-computed, right?

PR: #621. I just modified colspan and run `node build.js`; I hope that's all...

**Pull request merged**
