### PR TITLE
Adds Proxy.for to Proxy test

### PR DESCRIPTION
**Pull request by rwaldron**
My editor likes to remove empty ws lines, so that's in one commit, but the good stuff is in this commit:

https://github.com/rwldrn/es5-compat-table/commit/75c707f4b36747a917bdc2396be8e695f0fe5b32

### CODE REVIEW

**Comment by kangax** [comment]
Hey Rick, thanks! Do you know if this addition changes test results in any of the engines?

**Comment by rwaldron** [comment]
Nope, not yet anyway. Direct proxies is the newest edition. If you're considering dev builds, I can run through them this morning

**Comment by kangax** [comment]
That would be great. Just don't want test results to get out of sync.

**Comment by rwaldron** [comment]
Sure thing, I'll post back and update the PR with any results

**Comment by rwaldron** [comment]
Hah! Early morning cobwebs... of course it changes the current results. No one supports `Proxy.for`... yet. ;)

I'll update the table. Also, I have another patch for `const` and `let` coming, but my editor wants to strip those empty ws lines, so I'll wait until you make a call on that commit

**Comment by rwaldron** [comment]
Updated table

**Pull request merged**
