### PR TITLE
Add Template Literal Revision to ES2018 features

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://github.com/tc39/ecma262/pull/773#issuecomment-288177650

### CODE REVIEW

**Review by afmenez — APPROVED** [review]
LGTM

**Comment by afmenez** [comment]
On second thought, I wonder if this shouldn't go under "2018 misc" instead of "2018 features"...

**Comment by chicoxyzzy** [comment]
> I wonder if this shouldn't go under "2018 misc" instead of "2018 features"...

Not sure either

**Comment by afmenez** [comment]
Based on previous features classification, "2018 features" would be for entirely new features, like the SIMD proposal.  Refinements to existing features, like this one, would go under "2018 misc".  But I may have got it wrong.

**Review by ljharb — APPROVED** [review]
I think 2018 misc is more appropriate but I don't think it matters. Technically it is a feature since it enables DSLs that couldn't previously be implemented.

**Comment by chicoxyzzy** [comment]
OK, I'll merge this as is for now

**Pull request merged**
