### PR TITLE
Modify the super() code slightly so that Closure can compile it.

### PR DESCRIPTION
**Pull request by MatrixFrog**
To see what Closure compiles this to, you can use the Closure Compiler
debugger: http://goo.gl/CYL53X

### CODE REVIEW

**Comment by webbedspace** [comment]
If Closure can't handle having a class expression as the extends clause of another class expression, then it hasn't implemented `class` correctly.

Admittedly, this has no bearing on its implementation of `super()`, so I guess this pullreq is fair enough - but this probably means an additional class subtest (#280) may be needed to test the functionality of class-expression-in-extends.

**Comment by MatrixFrog** [comment]
We intentionally implemented only a subset of all valid `class` expressions, to keep the generated ES3 code simple.

**Comment by kangax** [comment]
Do we still need this?

**Comment by webbedspace** [comment]
Actually, I (or we) haven't yet rewritten the class tests to avoid using the problematic form, or making its usage a separate test. Obvs this particular pullreq no longer works (as the class test is now separate subtests).

**Comment by MatrixFrog** [comment]
Okay, closing this then.

**Pull request closed without merging**
