### PR TITLE
Add "JSON superset" tests to the ES2016+ tab

### PR DESCRIPTION
**Pull request by afmenez**
This is the only Stage 4 proposal that has no tests yet.  I ported both subtests from test262, so I believe they are correct.
I haven't run the tests on Safari, got the results from the release notes.

### CODE REVIEW

**Comment by afmenez** [comment]
I believe it works on Babel 7 too, but now I don't know how to add the results with the core2/core3 complication.

**Review by ljharb — APPROVED** [review]
Seems useful to maybe also add a test that utilizes JSON functions? LGTM otherwise

**Comment by afmenez** [comment]
Yes, it seemed strange to me that the test262 tests didn't mention any JSON. :)
The [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON#JavaScript_and_JSON_differences) says that `JSON.parse()` works on all browsers, but just newer browsers support `eval()`, so I assumed that was the important test.  But I don't know how to add JSON functions if they won't fail for old browsers.

**Comment by afmenez** [comment]
Please note [this comment](https://bugzilla.mozilla.org/show_bug.cgi?id=1435828#c15) on the Firefox bug:
"extend ECMA-262 syntax into a superset of JSON" is a somewhat obscure way to describe the *effect* of this change.  I would instead suggest:

"JavaScript string literals may now directly contain `U+2028 LINE SEPARATOR` and `U+2029 PARAGRAPH SEPARATOR`.  As a consequence, JSON syntax is now a subset of JavaScript literal syntax."

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
