### PR TITLE
correct results for Array.isArray and Date.prototype.toJSON for Safari/WebKit

### PR DESCRIPTION
**Pull request by claudepache**

### CODE REVIEW

**Comment by claudepache** [comment]
Something got wrong in e719425b36667b198fc96d5129b288313d831eef.

**Comment by ljharb** [comment]
Whoops, sorry about that!

**Comment by claudepache** [comment]
I've not re-built the html files after the correction, so `es5/index.html` has not been updated.

**Comment by ljharb** [comment]
Done!

**Pull request merged**
