### PR TITLE
Update Firefox results for the Set Methods feature

### PR DESCRIPTION
**Pull request by afmenez**
Ditto.

### CODE REVIEW

**Comment by afmenez** [comment]
Firefox 128 will be released tomorrow, it would be nice if this could be merged before that to avoid the conflicts.

**Comment by ljharb** [comment]
If that doesn't happen, you can either add to this PR, or base the new PR on top of this one?

**Comment by afmenez** [comment]
It's 3 different PRs that would be affected.  I'll hold the new one until all three are committed or rejected.

**Comment by afmenez** [comment]
Closing in favor of #1908 , which is more complete.

**Pull request closed without merging**
