### PR TITLE
Add Babel 7

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
I don't think babel 7 is out yet, and I don't think we should add it until it's out of beta.

**Comment by chicoxyzzy** [comment]
@ljharb it is marked as unstable so I think it should be ok to add it

**Review by ljharb — APPROVED** [review]
yeah ok fair

**Comment by zloirock** [comment]
IIRC some `babel@7` features already were added to `babel` column.

**Comment by chicoxyzzy** [comment]
@zloirock yes I removed numeric separators from Babel 6 column

**Pull request merged**
