### PR TITLE
Update Chrome 53-55

### PR DESCRIPTION
**Pull request by chicoxyzzy**
- mark Chrome 53 as Stable
- update Chrome 55 results
- small fixes for Chrome and Opera

### CODE REVIEW

**Comment by afmenez** [comment]
LGTM

**Comment by chicoxyzzy** [comment]
It looks like Chrome 55 enabled PTC by default so I think it's time to add it to table as well. I'll create new PR when this one will get merged

**Comment by chicoxyzzy** [comment]
Can we merge this? Chrome 53 is stable for more than 2 weeks

**Comment by chicoxyzzy** [comment]
It's strange but GitHub Pages site didn't update for some reason
image

However it looks fine in local build


and [index.html file](https://raw.githubusercontent.com/kangax/compat-table/gh-pages/es6/index.html) has all the changes. Is it GH Pages bug?

**Comment by mkurz** [comment]
It's published now.
I experienced the same behaviour with a GH-page of mine today. Looks like it takes a while to publish sites now... I hope GitHub will fix this so updated GH-pages will be in synch immediately.

**Comment by chicoxyzzy** [comment]
Lets wait for next build and mark this feature as flagged if it'll still not pass test

**Pull request merged**
