### PR TITLE
Firefox 90 released

### PR DESCRIPTION
**Pull request by afmenez**
Firefox 90 was released yesterday.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Indeed it was! FF v90 also includes support for `#x in obj`, and I think also `.at`?

**Comment by fgblomqvist** [comment]
Any reason this is not getting merged?

**Comment by ljharb** [comment]
@fgblomqvist our policy here is that two collaborators must review a PR for it to land.

**Comment by fgblomqvist** [comment]
@ljharb Very sensible! Just wasn't sure since no other reviewer was tagged 🙂

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
