### PR TITLE
[ES2016plus] Make the "IE 10 or older" definition clearer

### PR DESCRIPTION
**Pull request by mgol**

### CODE REVIEW

**Comment by zloirock** [comment]
Why do you think it's a typo?

**Comment by mgol** [comment]
Oh, does it mean "IE 10 or older?" With other columns sometimes using ranges it sounded to me as an unfinished "IE10 to something newer" range...

**Comment by zloirock** [comment]
Yep. Feel free propose something better readable.

**Comment by mgol** [comment]
I don't have better ideas, the `n-` shortcut is popular. It might be that I've seen specifically `IE10-11` before and just connected those two, maybe I'd understand it immediately otherwise. I'll close this PR then, sorry for the fuss.

**Comment by ljharb** [comment]
How about `IE <= 10` Or `IE < 11`?

**Comment by mgol** [comment]
That would work. :) With spaces?


## 

Michał Gołębiowski

**Comment by ljharb** [comment]
Probably with spaces, for readability?

**Comment by mgol** [comment]
PR updated with the changes proposed by @ljharb.

**Comment by ljharb** [comment]
LGTM

**Pull request merged**
