### PR TITLE
Fixing the result values for Firefox features marked as "nomob"

### PR DESCRIPTION
**Pull request by afmenez**
"flagged" means that the feature is not available by default, but it can be turned on by the user (either by changing the browser configuration or adding a command line parameter).  This is not what the "nomob" nightly means: the feature is available on desktop builds only, and there's no way to enable it on mobile builds.

This PR reverts a change made in #1438, but had no relation with the issue being fixed.

### CODE REVIEW

**Review by zloirock — CHANGES_REQUESTED** [review]
I think that it would be better to rename `flagged` to something else what will include controversial cases.

**Comment by afmenez** [comment]
I don't think "flagged" should go, we perhaps need a new value then, for features partially supported.  Notice that Firefox is the only browser where the features not available on all platforms are marked, the results for the other browsers simply assume the Desktop results are the ones that matter.

**Comment by zloirock** [comment]
However, I think that `nomob` / `nightly` / `developer` should be shown in the table like `flagged` now - as partially supported with `false` result.

**Comment by zloirock** [comment]
We need some kind of value which will mean "supported in some cases".

**Comment by afmenez** [comment]
My point exactly.

**Comment by afmenez** [comment]
Actually, most Firefox users are on Desktop.  By most I mean something like > 98%.  If the feature is available for >98% of the users, the result should be true, with a note saying where it is not.  As it was before, and as this PR reverts.

**Comment by zloirock** [comment]
"> 98%" does not mean "all" which by my meaning required for `true`. At least, it could cause problems for tools like `preset-env`.

**Comment by afmenez** [comment]
OK, in that case I believe "flagged" is good enough.  I am dropping this one.

**Pull request closed without merging**
