### PR TITLE
Adding note explaining global property reversal on Firefox and Webkit

### PR DESCRIPTION
**Pull request by afmenez**
Adding note explaining global property reversal on Firefox.

### CODE REVIEW

**Review by ljharb — COMMENTED** [review]
This is also the case for WebKit.

**Comment by afmenez** [comment]
Is there an issue open on their tracker?  Or can the same note be used for both browsers?

**Review by chicoxyzzy — COMMENTED** [review]
https://bugs.webkit.org/show_bug.cgi?id=165171

**Review by ljharb — APPROVED** [review]
LGTM.

The next Safari TP will undoubtedly need the same note as webkit.

**Pull request merged**
