### PR TITLE
Add Firefox 45 to the table

### PR DESCRIPTION
**Pull request by evilpie**

### CODE REVIEW

**Comment by evilpie** [comment]
@webbedspace @zloirock can you merge?

**Comment by zloirock** [comment]
LGTM. Thanks.

**Comment by evilpie** [comment]
@zloirock thanks

**Comment by kangax** [comment]
Hey @evilpie, if it's not too much hassle could you also specify how percentage changed with PR? It's always nice/convenient that way, instead of having to check before merging PR and then after.

**Pull request merged**
