### PR TITLE
ES2018 RegEx features enabled in Firefox 78

### PR DESCRIPTION
**Pull request by afmenez**
The RegEx engine was updated on Firefox Nightly, it now passes 3 of the 4 new RegEsx features in ES2018.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
These tests not pass for me on latest Nightly

**Comment by afmenez** [comment]
Curious, they do pass here.  Are sure you have today's build (12/may)?

**Comment by chicoxyzzy** [comment]
78.0a1 (2020-05-12) (64-bit)

**Comment by afmenez** [comment]
The patch was reverted and there was a new "nightly":
https://bugzilla.mozilla.org/show_bug.cgi?id=1634135#c24
So this can't go in for now.  Can we leave it here for a while until it is merged again?

**Review by chicoxyzzy — APPROVED** [review]
all features have arrived with latest Nightly

**Pull request merged**
