### PR TITLE
Adding results for Firefox 4..9

### PR DESCRIPTION
**Pull request by afmenez**
Adding/updating results for Firefox 4 to Firefox 9.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Just noticed that there is no such browser as `firefox4` in `esnext-browsers.js`. The lower version of FF there is 10

**Comment by chicoxyzzy** [comment]
Potentially this breaks previous valid results. @zloirock we should add FF4+ or revert this commit

**Comment by chicoxyzzy** [comment]
Confirmed. This breaks previous valid results for FF10+

**Comment by chicoxyzzy** [comment]
I've filed PR to fix this #873

**Comment by afmenez** [comment]
My bad, I didn't check all the outputs.  Sorry for that.

**Pull request merged**
