### PR TITLE
[ESNext] Iterator Helpers

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Comment by ljharb** [comment]
Is there a rush with all these PRs, that they need to land without review?

**Comment by zloirock** [comment]
Each of them was available for review within ~24 hours. If you wanted to add a review - you had enough time. I saw no reason to wait longer to add obvious tests. If you see any problems - you can add fixes in separate PRs.

**Comment by ljharb** [comment]
That's not how we've typically handled things in this repo; there's no "24 hour" policy, and 24 hours on a long weekend in the US isn't reasonable anyways.

Please do not merge any PRs unless two collaborators have signed off (or one, if the author is also a collaborator) - that matches the convention we've all followed here for years.

**Comment by zloirock** [comment]
I can not add new proposals at all and in this case, no one else will do it. Maybe instead of "reviewing" PR you will add [someting new](https://github.com/kangax/compat-table/pulls?q=is%3Apr+author%3Aljharb+is%3Aclosed)? Many proposals still are not added.

**Comment by ljharb** [comment]
The limits on my free time aren’t related to etiquette on PRs.

**Comment by zloirock** [comment]
But you insist that I wait for your free time for reviewing my PR in this repo? -) You can spend your time more profitably.

**Comment by ljharb** [comment]
Yes? That’s how open source projects with multiple maintainers work.

As i said, there’s no rush on any of these landing - no harm is done by delaying.

**Comment by zloirock** [comment]
Dear @ljharb, since your previous PR to this repo was in 2016, I don't think that you can be called a maintainer of this project. Just approving of PRs is not the maintenance. If you wanna maintain this project, please, try to maintain actual data in the repo, what I'm trying to do in PRs like this - a big part of them are obsolete.

**Comment by ljharb** [comment]
Making PRs is not solely what makes a maintainer - that is an incredibly hostile and exclusionary view.

Absolutely issue triage and PR review *alone* can make someone a maintainer.

**Comment by zloirock** [comment]
Without up-to-date data, there is no project. No one is engaged in adding new proposals. You wanna be a maintainer with the dead project?

**Comment by ljharb** [comment]
Historical data remains useful forever even if no new data is ever added.

I’m not saying it’s not great to have PRs come in - I’m saying that it’s not a requirement that all of us maintainers send those PRs, and that there’s no rush to merge them - it’s more important to give proper time for review.

**Comment by zloirock** [comment]
Dear @ljharb... Sorry for the delayed reply. A long weekend in the US? The limits on your free time aren’t related to etiquette on PRs? The next day I was able to be imprisonment for several years for manslaughter, so I didn't want to wait many days for useless reviews because was a chance that you could not see requested changes soon.

**Comment by ljharb** [comment]
the PRs can both wait several years if necessary, and can be updated by any maintainer - so there was still no rush.

**Comment by zloirock** [comment]
🤦

**Pull request merged**
