### PR TITLE
Promote RegExp features to stage 3

### PR DESCRIPTION
**Pull request by chicoxyzzy**
according to https://github.com/tc39/proposals/commit/e0bef6932441300cd54b8c0aed6d591e8a18a752

### CODE REVIEW

**Comment by afmenez** [comment]
I was about to do this too.  Why was it dropped?

**Comment by chicoxyzzy** [comment]
@afmenez what do you mean by dropped?

**Comment by afmenez** [comment]
It shows a red "x" in the patch and says this branch was deleted, so I assumed this was dropped.  But I see that the feature was indeed promoted already. :)

**Comment by ljharb** [comment]
The x is because the PR was merged before tests finished (we probably shouldn't be doing that), and the branch was deleted after merging.

**Comment by chicoxyzzy** [comment]
Yes Jordan is right. I run tests locally but I agree that I shouldn't have merge branch before tests pass on CI

**Pull request merged**
