### PR TITLE
Add es7-shim to es7 compat table

### PR DESCRIPTION
**Pull request by ljharb**
https://www.npmjs.com/package/es7-shim

### CODE REVIEW

**Comment by kangax** [comment]
Need to change data-es7.js as well, or all of this will be overwritten on the next "compile". Check out https://github.com/kangax/compat-table#editing-the-tests

**Comment by ljharb** [comment]
ah, thanks, i just used the web ui. I'll clone the repo properly and fix it today.

**Comment by ljharb** [comment]
@kangax so, the es7-shim doesn't auto-shim unless you run it through browserify (which thus automatically autoshims). Is there a way I can specify this behavior? Is there a reason that all polyfills aren't run through browserify already?

**Comment by ljharb** [comment]
nvm, i found the array in build.js.

**Comment by ljharb** [comment]
All updated!

**Comment by kangax** [comment]
LGTM, thanks!

@webbedspace mind taking a look if all is good?

**Pull request merged**
