### PR TITLE
Fixed - call new Function in perspective

### PR DESCRIPTION
**Pull request by lenville**
As above, the [original](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=console.log%28%20function%28%29%20%7B%0D%0A%09const%20baz%20%3D%201%3B%0D%0A%09try%20%7B%0D%0A%09%09Function%28%22const%20foo%20%3D%201%3B%20foo%20%3D%202%3B%22%29%28%29%3B%0D%0A%09%7D%20catch%28e%29%20%7B%0D%0A%09%09return%20true%3B%0D%0A%09%7D%0D%0A%7D%28%29%20%29%3B) doesn't work well in Babel run-time.
Fixed one is [here](http://babeljs.io/repl/#?experimental=true&playground=true&evaluate=true&loose=false&spec=false&code=console.log%28%20function%28%29%20%7B%0D%0A%09const%20baz%20%3D%201%3B%0D%0A%09try%20%7B%0D%0A%09%09Function%28%22const%20foo%20%3D%201%3B%22%2C%20%22foo%20%3D%202%3B%22%29%28%29%3B%0D%0A%09%7D%20catch%28e%29%20%7B%0D%0A%09%09return%20true%3B%0D%0A%09%7D%0D%0A%7D%28%29%20%29%3B).

### CODE REVIEW

**Comment by zloirock** [comment]
[In order to test compilers](https://github.com/kangax/compat-table#in-order-to-test-compilers)

> Note that some tests cannot be compiled correctly, as they rely on runtime eval() results to ensure that, for instance, certain syntactic constructs are syntax errors. These will fail on the compiler test pages. Support for those features should be divined manually.

`Function("const foo = 1;", "foo = 2;")()` is equal of this invalide code:

``` js
(function(const foo = 1;){
  foo = 2;
})();
```

You do not mistake? :)

**Comment by lenville** [comment]
I'm so sorry about not reading that note and I'll check it up again.

In started focusing on es6 in about half a month ago. For now, I've watched some videos from Brendan Eich, Jack Franklin, etc. Also, I've read lukehoban's [es6features](https://github.com/lukehoban/es6features) and Sayanee Basu's [Use ECMAScript 6 Today](https://code.tutsplus.com/articles/use-ecmascript-6-today--net-31582), but I found it difficult to know more details about the latest standards. So I started to explore this compat-table to learn more about es6.

As a newbie here, I must say sorry again for disturbing you and for my poor English as a non-native speaker. I mean no harm to this community.

I'd like to seek for some suggestions to go on learning es6 or just a simple learning road-map. Would anyone here mind helping me out? : )

**Comment by zloirock** [comment]
@lenville I do not know. I do not speak English :) Maybe [Understanding ECMAScript 6](https://leanpub.com/understandinges6/read)?

**Comment by lenville** [comment]
@zloirock Cool! I'll read it. And I found [Understanding ECMAScript 6](https://github.com/nzakas/understandinges6) by Nicholas C. Zakas would help.

**Pull request closed without merging**
