### PR TITLE
Chrome 72 release + Chrome 74 Canary

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by zloirock** [comment]
image
?

**Comment by chicoxyzzy** [comment]
@zloirock all builds of Chrome except iOS and cross builds has been updated
https://omahaproxy.appspot.com

**Comment by zloirock** [comment]
@chicoxyzzy yep, just now, already after merging this PR.

**Comment by chicoxyzzy** [comment]
macOS and linux builds was released at least 4 hours ago. Android and Windows version (which are always get released first) was definitely updated before this PR was merged

**Comment by zloirock** [comment]
3-4 hours ago some builds, release on https://chromereleases.googleblog.com/ and auto update on all my devices were missing.

**Comment by chicoxyzzy** [comment]
¯\\\_(ツ)_/¯

According to https://omahaproxy.appspot.com/history first stable versions started to rollout at 17:12 (UTC?)

**Comment by chicoxyzzy** [comment]
Not sure how but I also just got this.

image

omahaproxy still mentions 71 as latest stable for iOS 🤔

**Pull request merged**
