### PR TITLE
add some Function.prototype.toString tests

### PR DESCRIPTION
**Pull request by michaelficarra**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
This LGTM but it'd be good to add some human-readable tests as well, for common (non-unicode char) cases.

**Comment by michaelficarra** [comment]
@ljharb It's a bit hard to do that since the tests involve preserving comments and I have to write the whole test inside of a comment :confused:.

**Comment by ljharb** [comment]
Sure, but not every engine passes `Function.toString.call(class Foo{}).startsWith('class Foo')` either :-/

**Comment by michaelficarra** [comment]
Okay, would you like them in addition to these or in place of them?

**Comment by ljharb** [comment]
Oh, in addition to, more tests are better :-)

**Comment by michaelficarra** [comment]
@ljharb Okay, I added a few simple tests, one of which even IE11 passes!

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
