### PR TITLE
declare traceur, phantom.js, and besen as obsolete

### PR DESCRIPTION
**Pull request by dnalborczyk**
I think it's pretty safe to say that we won't expect any additions, changes from Traceur, Phantom.js, and Besen. As a bonus it'll also create more space for the test result table to display.

**Traceur**, last commit Sep 15, 2016
https://github.com/google/traceur-compiler

**Phantom.js** (unmaintained, some sporadic commits in June)
maintainer stepped down with the advent of Headless Chrome.
https://groups.google.com/forum/#!topic/phantomjs/9aI5d-LDuNE
https://github.com/ariya/phantomjs

**Besen**, last commit April 23, 2016
https://github.com/BeRo1985/besen

### CODE REVIEW

**Comment by ljharb** [comment]
(replaces #1162)

**Review by ljharb — CHANGES_REQUESTED** [review]
"no more maintenance" doesn't necessarily mean it's obsolete; headless chrome can't yet replace phantom, so I'd say phantom is still not obsolete.

I think an ES5 engine is clearly obsolete - but altho Traceur indeed no longer seems to be under active development, I'm not sure if "obsolete" applies yet.

**Comment by zloirock** [comment]
I agree with @ljharb.

**Comment by afmenez** [comment]
The Phantom.js part was already merged with  #1364, the other two need updating.

**Pull request closed without merging**
