### PR TITLE
Add more computed properties tests

### PR DESCRIPTION
**Pull request by kangax**
Add "computed shorthand methods" and "computed accessors" tests.

### CODE REVIEW

**Comment by kangax** [comment]
@webbedspace I've added 2 more "computed properties" tests. Please double-check if everything looks fine. What's interesting is that Chrome currently supports `{ [x]: ... }` notation but not `{ [x]() { ... } }` one (Firefox is OK). There's at least 1 more test we could add — computed generator `{ * [Symbol.iterator]() { yield 'foo' }` but I'm not sure if putting it under object literal extensions makes sense (it's really a combination of 2 features; but then, so is computed shorthand methods...)

**Comment by kangax** [comment]
@webbedspace I also didn't have a chance to test IETP yet

**Comment by webbedspace** [comment]
Let's see here...
- FF does _not_ support computed accessors until FF34.
- IETP supports all object literal extensions.
- If you look closely, there's already a shorthand generator test, so a computed shorthand generator test would fit next to it.

**Comment by webbedspace** [comment]
@kangax Merge conflict resolved.

**Comment by kangax** [comment]
thanks @webbedspace!

**Pull request merged**
