### PR TITLE
Revert "update 6to5's Symbol compatibility"

### PR DESCRIPTION
**Pull request by chicoxyzzy**
I had pushed [that commit](https://github.com/kangax/compat-table/commit/b03caff1ef3efaaf816a1f5d89b999471b292c5d) by mistake. I just noticed that actually this features doesn't on IE and Safary so changes should be reverted.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
you can test [this 6to5's REPL example](http://6to5.org/repl/#?experimental=true&playground=true&evaluate=true&loose=false&code=let%20foo%20%3D%20Symbol%28'foo'%29%3B%0Aconsole.log%28String%28foo%29%3D%3D%3D'Symbol%28foo%29'%29%3B%0Atry%20%7B%0A%20%20console.log%28foo%20%2B%20%22%22%29%3B%0A%7D%20catch%20%28e%29%20%7B%7D%0Atry%20%7B%0A%20%20console.log%28foo%20%2B%200%29%3B%0A%7D%20catch%20%28e%29%20%7B%7D) in IE and Safary

**Comment by chicoxyzzy** [comment]
ping @kangax @webbedspace 

BTW sorry for my last PR, I should test things better before sending new pull requests :disappointed:

**Comment by kangax** [comment]
Hm, how come data-tally went from 0.7 to 0.5 in this revert, while original commit had 0.7 -> 1? Is it because of intermediate changes?

**Comment by chicoxyzzy** [comment]
@kangax its because of [this merged PR](https://github.com/kangax/compat-table/commit/1afa3e1ccd686fa392cf5d615c5e71c49f97b8a6)

**Pull request merged**
