### PR TITLE
BigInt is enabled by default in Firefox Nightly

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://bugzilla.mozilla.org/show_bug.cgi?id=1531293

I don't like how results look with this PR though.

image

image

### CODE REVIEW

**Comment by zloirock** [comment]
Maybe makes sense change the value of `firefox.nightly` to `flagged`?

**Comment by afmenez** [comment]
`firefox.nightly` normally means that the feature is only available on nightly builds.  `BigInt` is also available on beta with the flag enabled, so it should be `flagged` on 57, and `true` on 58.

**Comment by zloirock** [comment]
@afmenez it will cause a problem with marking previously nightly versions as stable.

**Comment by afmenez** [comment]
I don't agree with the latest patch.  This is not actually a "nightly" feature.  All the features previously marked as "nightly" were only available on nightly builds (and most of them always on), and they were removed when the version was promoted to beta.  BigInt on the other hand is flagged on beta and on by default on nightly, so why not just set firefox68 to true?

**Review by zloirock — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
@afmenez because as @zloirock said, the feature is not in Firefox 68 (which will be stable and beta and not necessarily will have feature support in such versions), but just Firefox 68 Nightly

**Comment by chicoxyzzy** [comment]
@ljharb PTAL at [last commit](https://github.com/kangax/compat-table/pull/1438/commits/505fc1a8870b60f3270b7c356640ef2f1f2ff512) when you'll have time

**Review by ljharb — APPROVED** [review]

**Pull request merged**
