### PR TITLE
Updated Konqueror results to 4.13

### PR DESCRIPTION
**Pull request by webbedspace**
Results obtained via browsershots.net.

### CODE REVIEW

**Comment by kangax** [comment]
nice, thanks!

**Comment by webbedspace** [comment]
Just for reference: it's not a mistake that KQ4.13 is listed as supporting Math.acosh but not Math.asinh. As you can see [here](http://marc.info/?l=kde-commits&m=139014989807635&w=2), "asinh" was typoed in the commit that introduced it. :P

**Comment by kangax** [comment]
That's amazing :) I'm also quite surprised to see _any_ ES6 support in KQ at all... I was under impression it's not actively developed, basically dying; even considered dropping it from the tables at some point. I mean, they don't even have full ES5 support — http://kangax.github.io/compat-table/es5/#konq49 — or at least _didn't_ have. Speaking of that, we should update ES5 table as well. I imagine all of those red ones are now green?

**Comment by webbedspace** [comment]
Well, I just ran it through browsershots.org (not .net, sorry) and... [you're right](http://i.imgur.com/ZvPwywM.png). Everything except strict mode and zero-width chars.

Incidentally, if you're looking for things to axe, I've been lately wondering whether Rhino should be dropped or replaced with Nashorn...

**Comment by Mouvedia** [comment]
@webbedspace I am curious, do you have intermediate results between version 4.9 and 4.13?
I am trying to find the first ES5 ready version of Konqueror (KHTML).

**Pull request merged**
