### PR TITLE
Splitting Opera from Chrome

### LINKED ISSUE #1126: Split Opera results from Chrome
Opera is one of the many browsers derived from the Chrome engine, but it is the only one attached to it in the result tables.   I believe Opera results should be at least split, and maybe even dropped from the tables.

### PR DESCRIPTION
**Pull request by afmenez**
Fixes #1126

### CODE REVIEW

**Comment by ljharb** [comment]
How does this affect what results show up for opera, since it's been inheriting the chrome results thus far?

**Comment by afmenez** [comment]
```
  "opera15": {
    "full": "Opera 15",
    "family": "V8",
    "equals": "chrome23",
    "short": "OP 15",
    "obsolete": "very"
  },
```
The tag "equals" links to the Chrome version it was associated to previously.

**Review by ljharb — APPROVED** [review]
Perfect, thanks!

**Review by chicoxyzzy — APPROVED** [review]
I think that we should remove release and retire dates for Chrome 81+ and remove Chrome 82 from `environments.json`, but this could be done in separate PRs

**Comment by afmenez** [comment]
The date removals belong to a separate PR, but I am not sure if 82 should be removed.  Maybe `obsolete:very` AND `unstable:true`?

**Comment by chicoxyzzy** [comment]
Chrome 82 release will be skipped https://groups.google.com/a/chromium.org/forum/#!msg/chromium-dev/Vn7uzglqLz0/JItlSrZxBAAJ

**Comment by chicoxyzzy** [comment]
Sorry, not Chrome, but Chromium 82

**Pull request merged**
