### PR TITLE
Adding Edge 16 Preview, fixing flagged links

### LINKED ISSUE #1110: Add Edge 16 Insider Preview
https://blogs.windows.com/windowsexperience/2017/06/08/announcing-windows-10-insider-preview-build-16215-pc-build-15222-mobile/#6uif7A5XjXUPok7l.97

https://developer.microsoft.com/en-us/microsoft-edge/platform/changelog/desktop/16215/?compareWith=15063

### PR DESCRIPTION
**Pull request by afmenez**
The Edge 16 Insiders Preview is already available, adding it to the tables.  I am also retiring some ancient versions of IE.
Finally, I am updating the flagged Edge features to link to the notes, as in the other browsers.
This PR fixes #1110.

### CODE REVIEW

**Comment by afmenez** [comment]
Before anyone asks, I am not sure why I didn't retire IE10 too, since it was EOLed at the same time as IE8 and IE9.  What do you think?

**Comment by ljharb** [comment]
I think we may want to have separate PRs for the edge changes, and the browser changes.

**Comment by afmenez** [comment]
OK, this patch is now Edge-only.

**Review by ljharb — APPROVED** [review]

**Review by chicoxyzzy — APPROVED** [review]
LGTM

**Pull request merged**
