### PR TITLE
[ES6] Added JavaScript Automation for OS X

### PR DESCRIPTION
**Pull request by fallroot**
I tested compatibility by following code.
- OS X 10.11.3
- node 5.5.0

```
function prehandleWithJxa(es6) {
  es6.tests.forEach(function(test) {
    if (test.subtests) {
      test.subtests.forEach(function(subtest) {
        var fn = subtest.exec;

        if (typeof fn === 'function') {
          var expr = (fn + '').match(/[^]*\/\*([^]*)\*\/\}$/);

          if (!expr) {
            return;
          }

          subtest.res.jxa = true;

          var fpath = os.tmpDir() + path.sep + 'temp.js';
          var file = fs.writeFileSync(fpath, `(function(global){global.__createIterableObject=function(arr, methods){methods=methods||{};if(typeof Symbol!=='function'||!Symbol.iterator){return{};}arr.length++;var iterator={next:function(){return{value:arr.shift(),done:arr.length<=0};},'return':methods['return'],'throw': methods['throw']};var iterable={};iterable[Symbol.iterator]=function(){return iterator;};return iterable;};${expr[1]}})(this);`);

          try {
            child_process.execSync(`osascript -l JavaScript ${fpath}`);
          } catch(e) {
            subtest.res.jxa = false;
          }
        }
      });
    }
  });
}
```

### CODE REVIEW

**Comment by webbedspace** [comment]
Please rerun the Promise tests using different code, as they are async and do not immediately yield results.

**Comment by fallroot** [comment]
@webbedspace You're right. But Promise is not supported in JXA yet. Though above test code should be corrected, files in this commit would be unchanged.

**Comment by fallroot** [comment]
Fixed test code.

```
var createIterableObjectString = `global.__createIterableObject = function(arr, methods) {
  methods = methods || {};
  if (typeof Symbol !== 'function' || !Symbol.iterator) {
    return {};
  }
  arr.length++;
  var iterator = {
    next: function() {
      return { value: arr.shift(), done: arr.length <= 0 };
    },
    'return': methods['return'],
    'throw': methods['throw']
  };
  var iterable = {};
  iterable[Symbol.iterator] = function(){ return iterator; }
  return iterable;
}`;

var asynsTestPassedString = `var asyncTestPassed = (function(name, subname) {
  return function() {
    console.log(name, subname, ' passed');
  }
})`;

function prehandleWithJxa(es6) {
  es6.tests.forEach(function(test) {
    if (test.subtests) {
      test.subtests.forEach(function(subtest) {
        var fn = subtest.exec;

        if (typeof fn === 'function') {
          var expr = (fn + '').match(/[^]*\/\*([^]*)\*\/\}$/);

          if (!expr) {
            return;
          }

          subtest.res.jxa = true;

          var fpath = os.tmpDir() + path.sep + 'temp.js';
          var file = fs.writeFileSync(fpath, `(function(global){
            ${createIterableObjectString};
            ${asynsTestPassedString}('${test.name}','${subtest.name}');
            ${expr[1]};
          })(this);`);

          try {
            child_process.execSync(`osascript -l JavaScript ${fpath}`);
          } catch(e) {
            subtest.res.jxa = false;
          }
        }
      });
    }
  });
}
```

**Comment by webbedspace** [comment]
Could you rebase this with f579da25f7, please?

**Comment by fallroot** [comment]
OK, rebased.

**Pull request merged**
