### PR TITLE
Add samsung 16-19 data

### PR DESCRIPTION
**Pull request by JLHwung**
Added samsung 16 - 18.

The release data and Chromium version is extracted from https://en.wikipedia.org/wiki/Samsung_Internet.

### CODE REVIEW

**Review by zloirock — CHANGES_REQUESTED** [review]
image

https://play.google.com/store/apps/details?id=com.sec.android.app.sbrowser&hl=en&gl=US

**Comment by ljharb** [comment]
I'm confused; you want to block Samsung 16-18 data being added until v19's data can be added to? This seems like a strict improvement even if it doesn't close every gap.

**Comment by zloirock** [comment]
Samsung 19 mapping is present at the same place where 16-18 mapping was found, it's something that can be added for some seconds, and that significantly improves this PR - so yes. Also, it's related to the `obsolete` field.

**Comment by ljharb** [comment]
The question isn't what would improve the PR, it's "is the PR an improvement", which it is. Placing the burden on PR authors to go *further* seems like it will just discourage contributions.

**Review by ljharb — APPROVED** [review]

**Comment by zloirock** [comment]
Don't write nonsense. If it can be improved at a negligible cost, it must be improved. If the contributors don't do it - who will - you? The practice shows that not. Otherwise, users of the project will receive incomplete content.

**Comment by ljharb** [comment]
It's not nonsense. In no way "must" something happen just because it "can" happen.

If it's something you want done, *you* do it. They're already receiving incomplete content - "complete" isn't a binary. This PR, as-is, will give them *more* complete content.

**Comment by zloirock** [comment]
This position is one of the reasons why the quality of the table content has fallen to an unacceptable level.

**Comment by ljharb** [comment]
Given the continued usage of the table and continued lack of complaints about it, it seems like you're the only one who finds it "unacceptable" - but again, if you want the quality "raised", feel free to make a PR to do so.

**Comment by zloirock** [comment]
[The perfect content quality - and the same in **many** other places.](https://github.com/kangax/compat-table/blob/bfc04568613d7b7e01ee46d3f7de3e24f3387e18/environments.json#L4193) Do you remember that you reverted commits where I fixed it?

Where in the table are modern features that already became stable, like `%TypedArray%.prototype.findLast`, or [any](http://kangax.github.io/compat-table/esnext/) stage 3 [proposals](https://github.com/tc39/proposals#stage-3) that were added after I added something to the table?

Why I don't see any mentions of `compat-table` in blog posts / social media for some years when some years ago I saw it each week?

Why Babel maintainer that opened this PR is forced to improve critically obsolete (about 2 years) data?

Why I was forced to start maintaining my own compat database for ensuring proper poyfilling in `preset-env` and related projects when data from this table was incomplete and improvements were blocked?

The perfect quality -) You almost killed this project.

**Comment by zloirock** [comment]
image

+800 (stable) -> +140 stars for a year.
+200 (stable) -> +30 forks for a year.

Excellent indicators.

**Comment by JLHwung** [comment]
Thanks! Added samsung 19 data.

**Review by zloirock — APPROVED** [review]

**Comment by ljharb** [comment]
> Why I don't see any mentions of compat-table in blog posts / social media for some years when some years ago I saw it each week?

Because engines are doing a much better job than they used to be at keeping up to date and aligned - thanks to this table - and so it's not as useful to discuss anymore.

> Why Babel maintainer that opened this PR is forced to improve critically obsolete (about 2 years) data?

Presumably because there aren't enough users on these platforms to have filed issues, and so nobody noticed.

@JLHwung thanks for adding the extra data!

**Comment by zloirock** [comment]
> Because engines are doing a much better job than they used to be at keeping up to date and aligned - thanks to this table - and so it's not as useful to discuss anymore.

Of course, there are no any posts about new JS features (that are now added even a little more actively than some years ago) like `Array#group`, "change array by copy", etc. that are still supported just by a part of engines -) There are even more such posts now than before - but there are no links to the `compat-table`.

> Presumably because there aren't enough users on these platforms to have filed issues, and so nobody noticed.

Perfectly - but it's the job of maintainers to monitor it - at least, no one forbid to do it [automatically](https://github.com/zloirock/core-js/blob/master/scripts/check-compat-data-mapping.mjs).

**Comment by ljharb** [comment]
MDN is often incorrect, so I'm surprised you're delegating to it as a source of truth, but ok.

**Comment by zloirock** [comment]
It's not a delegation - it's a notification about new versions - and after this notification, it's checked / added manually.

**Pull request merged**
