### PR TITLE
Set sticky categories in the table

### PR DESCRIPTION
**Pull request by JoCat**
before:
image

after:
image

### CODE REVIEW

**Comment by ljharb** [comment]
It's tough to review this one without a page to demo it out on.

**Comment by JoCat** [comment]
@ljharb https://jocat.github.io/compat-table/es6/

**Review by afmenez — APPROVED** [review]

**Comment by ljharb** [comment]
hmm, i'm not seeing any difference on safari between https://jocat.github.io/compat-table/es6/ and https://kangax.github.io/compat-table/es6/. what should i be looking for?

**Comment by afmenez** [comment]
When you scroll the table horizontally, the section titles now stay in place.

**Review by ljharb — APPROVED** [review]
nice, looks great

**Review by chicoxyzzy — APPROVED** [review]
perfect!

**Comment by JoCat** [comment]
Thanks :3

**Pull request merged**
