### PR TITLE
Class static initialization blocks support in Chrome 94

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://bugs.chromium.org/p/v8/issues/detail?id=11375#c4

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
i mean i guess, but it seems premature before it's actually released - things get pulled from the release train all the time.

**Comment by chicoxyzzy** [comment]
It works on Canary Version 94.0.4595.3 (Official Build) canary (x86_64) for me

**Comment by ljharb** [comment]
Sure, but things can still be pulled from canary too. There’s no rush really, is there?

**Comment by chicoxyzzy** [comment]
The proposal is enabled in Chrome 94 Dev and Canary is 95 now, so I think we can merge this now

**Comment by ljharb** [comment]
It’s fine, but I’d intended it to wait until release. Dev/canary don’t really count.

**Pull request merged**
