### PR TITLE
Mark IE 9 and 10 as obsolete in all tabs

### LINKED ISSUE #861: What is the policy for retiring a browser to "obsolete : very"?
There seems to be an excessive number of Firefox and Chrome versions active, which make the download bigger and the page slower.  What is the policy for retiring a browser with "obsolete : very"?

### PR DESCRIPTION
**Pull request by chicoxyzzy**
fixes https://github.com/kangax/compat-table/issues/861#issuecomment-252120515

### CODE REVIEW

**Review by afmenez — CHANGES_REQUESTED** [review]
Nice job, but you missed the Intl and Non-Standard tabs...

**Comment by afmenez** [comment]
LGTM.

**Review by afmenez — APPROVED** [review]

**Comment by zloirock** [comment]
MS still support IE maximal for supported platforms. For Vista it's IE9.

**Comment by chicoxyzzy** [comment]
@zloirock that's true but why does IE 9 and 10 marked as obsolete in es6 and esnext-browsers?

**Comment by zloirock** [comment]
I don't know.

**Comment by afmenez** [comment]
It seems IE9 and IE10 are still supported after all:
http://www.welivesecurity.com/2016/01/12/microsoft-ends-support-for-old-internet-explorer-versions/

**Comment by chicoxyzzy** [comment]
My main goal here is to make things consistent. Let's decide do we want to mark IE 9-10 as obsolete or stable.

**Comment by afmenez** [comment]
It is not clear to me what "stable" means, But IE9 and IE10 are still supported on some platforms, and are actually the latest available version for them.  So it seems that for now they are stable indeed.

**Comment by chicoxyzzy** [comment]
Looks like @webbedspace introduced changes for IE 10 (https://github.com/kangax/compat-table/commit/e085bc440252a449d033c3d32f4a721520f10956)

**Comment by chicoxyzzy** [comment]
did @jdalton said that IE 9-10 is unsupported? https://github.com/babel/babel-preset-env/issues/15

**Comment by jdalton** [comment]
Ya, IE9 is an odd one. While IE10 is dropped, IE9 technically still lingers for the Vista SP2 EOL (April 2017). However, the usage of Vista is so low that our guidance to devs is to consider it dropped already.

**Pull request merged**
