### PR TITLE
Add a "test-" prefix so that things like "Symbol" don't shadow the global Symbol

### LINKED ISSUE #477: IDs that match global names conflict - add a prefix?
`<td id="SIMD">` will shadow the global `SIMD` object. Either the test needs refinement, or the ID needs to not be "SIMD"

### PR DESCRIPTION
**Pull request by ljharb**
I'm not sure how any of these Symbol tests are marked as "passed" for anyone, since clearly nobody verified them in the browser :-)

Fixes #477.

### CODE REVIEW

**Comment by ljharb** [comment]
I'll merge this in an hour or so unless there's objections.

**Comment by kangax** [comment]
Dear god, how did this get through in the first place... Good catch, thanks!

Related: http://kangax.github.io/domlint/ that I made like... forever ago :)

**Comment by webbedspace** [comment]
Small problem: hyperlinks to specific rows (such as [this](https://kangax.github.io/compat-table/es6/#Symbol)) no longer scroll to them, because the old IDs were being used as URL fragment references. At the least, all the generated `<a>` anchor links need updating too.

**Comment by ljharb** [comment]
aha, thanks - I'll fix that now

**Comment by ljharb** [comment]
k, that should be consistent, and apply the same "test-" prefix to subtest IDs.

**Pull request merged**
