### PR TITLE
chore(data-esnext): Safari TP Named Capture Groups

### PR DESCRIPTION
**Pull request by keithamus**
image

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
This will need the build process ran first.

**Comment by keithamus** [comment]
Done 😄

**Review by chicoxyzzy — APPROVED** [review]
LGTM

**Comment by afmenez** [comment]
This updates the results without updating the title, which means the table is now wrong.  There was a PR #1185 fixing the results AND the header pending for more than 2 weeks.

**Comment by keithamus** [comment]
Sorry @afmenez I didn't notice that.

**Pull request merged**
