### PR TITLE
SharedArrayBuffer is re-enabled in Chrome 68

### PR DESCRIPTION
**Pull request by chicoxyzzy**

### CODE REVIEW

**Review by ljharb — CHANGES_REQUESTED** [review]
I get `ReferenceError: SharedArrayBuffer is not defined` in my Chrome 68; are you sure it's not behind a flag?

**Comment by chicoxyzzy** [comment]
@ljharb I have default settings in my Chrome
image

**Comment by chicoxyzzy** [comment]
https://bugs.chromium.org/p/chromium/issues/detail?id=821270

**Comment by ljharb** [comment]
> Current plan is to re-enable post M67 launch via Finch, pending strong enough stability signals on site-isolation.

This implies it's going to be turned on via some kind of live configuration feature, but that it's off by default.

**Comment by chicoxyzzy** [comment]
https://twitter.com/kennethrohde/status/1024046327750123520

**Comment by chicoxyzzy** [comment]
@ljharb do you have same version as me? I'm pretty sure that 68.0.3440.75 has SAB enabled by default on my laptop.

**Comment by ljharb** [comment]
`Version 68.0.3440.75 (Official Build) (64-bit)`

**Comment by chicoxyzzy** [comment]
Also just found this https://groups.google.com/a/chromium.org/d/msg/blink-dev/wvV42Hxct3g/7BNbpTs5BQAJ

**Comment by chicoxyzzy** [comment]
V8 team members confirmed that SAB was enabled in Chrome 68
https://groups.google.com/a/chromium.org/d/msg/blink-dev/wvV42Hxct3g/sxzY7KZbCgAJ

**Review by ljharb — APPROVED** [review]
Relaunching chrome did it.

I think we should probably add a note here tho, that this feature is remotely controlled and is not solely dependent on browser version.

**Comment by chicoxyzzy** [comment]
That's interesting. Probably we also should find what other features could be controlled remotely. I'll merge this for now.

**Pull request merged**
