### PR TITLE
Implement the Well-formed JSON.stringify tests

### PR DESCRIPTION
**Pull request by afmenez**
I am trying to implement the Well-formed `JSON.stringify` tests, but I have some questions:

- Are the tests correct?  I had to change the tests from the specification a little to get coherent results;
- Implemented both subtests from the specification, but the first one seems to pass on all browsers.  Is it necessary?
- I don't have the results for Safari, can anyone run it?
- I only have the results for the current version of Chrome, can anyone run on older versions?  Maybe newer?
- I have added significance: 'small' but I am not sure what is the relative importance of this feature;

TIA

### CODE REVIEW

**Comment by ljharb** [comment]
cc @mathiasbynens

**Comment by chicoxyzzy** [comment]
@afmenez we use spaces everywhere. In your PR there is mix of tabs/spaces. Same in 
https://github.com/kangax/compat-table/pull/1368

**Comment by mathiasbynens** [comment]
The `JSON.stringify('𝌆') === '"𝌆"'` test is not actually part of the proposal; it has always been the `JSON.stringify` behavior.  The proposal only changes the meaning of lone surrogates.

**Comment by mathiasbynens** [comment]
@afmenez Re:

> I don't have the results for Safari, can anyone run it?

FWIW, with jsvu + eshost-cli you can easily run a given snippet of JS code in any major JavaScript engine from the command-line (even on Windows): https://github.com/GoogleChromeLabs/jsvu#integration-with-eshost-cli Might be helpful in the future.

**Comment by mathiasbynens** [comment]
> I only have the results for the current version of Chrome, can anyone run on older versions? Maybe newer?

The proposal shipped in Chrome 72.

**Comment by afmenez** [comment]
Assuming the `significance: 'small'` is correct, I believe this is now ready to merge.

**Comment by afmenez** [comment]
Rebased.  I believe this is ready to get merged, did I miss something?

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
