### PR TITLE
Fix MDN logo path

### PR DESCRIPTION
**Pull request by chicoxyzzy**
There was wrong path for MDN logo. I fixed it.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
sad to use a relative URL, but you're right that this works

**Comment by ljharb** [comment]
We should probably set the base href so that `/mdn.png` works.

**Comment by chicoxyzzy** [comment]
@KTamas could you review this PR?

**Comment by chicoxyzzy** [comment]
I created new issue about base href https://github.com/kangax/compat-table/issues/1065

**Pull request merged**
