### PR TITLE
Firefox 55 release

### PR DESCRIPTION
**Pull request by afmenez**
Firefox 55 will be released today.  Updating tags, adding new versions and retiring old ones.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
According to [calendar](https://wiki.mozilla.org/RapidRelease/Calendar) it'll be releases on August 8

**Comment by afmenez** [comment]
Yes, and it says right there in the "release" tag, which I have added myself.  I need more sleep. :)
Sorry for jumping the gun on this one, should I retire the PR or let it rot here until next week?

**Comment by chicoxyzzy** [comment]
We can merge it when Firefox 55 will be released. Let's keep this PR and hope there won't be conflicts :)

**Review by ljharb — APPROVED** [review]
+1 on waiting til actual release

**Review by chicoxyzzy — APPROVED** [review]

**Comment by afmenez** [comment]
Tks!

**Pull request merged**
