### PR TITLE
updated closure to v20160125

### PR DESCRIPTION
**Pull request by oldergod**

### CODE REVIEW

**Comment by zloirock** [comment]
Please, fix linting: 51+ (!!!) duplicate keys.

**Comment by oldergod** [comment]
Sorry, I tried to automate the fillings but did not go that well. Should be good now.

**Comment by zloirock** [comment]
Stop... I checked just syntax. Why do you add standard library features? Looks like need revert it.

**Comment by oldergod** [comment]
I am not following, which features are you talking about?

**Comment by zloirock** [comment]
Typed Arrays, Map, Set, etc...

**Comment by oldergod** [comment]
Because Closure did add many polyfills recently : https://github.com/google/closure-compiler/tree/master/src/com/google/javascript/jscomp/js/es6

**Comment by zloirock** [comment]
But definitely not typed arrays. [You should run tests in an ES5-only engine, for example, IE9.](https://github.com/kangax/compat-table#in-order-to-test-compilers) Reverted. Please, fix the results.

**Comment by oldergod** [comment]
Alright, I'll look into that. thank you.

**Comment by zloirock** [comment]
BTW looks like closure test page broken - compile error for all tests.

**Comment by oldergod** [comment]
If I'm not mistaken, closure test page has never been used and this test suite has been built instead https://github.com/teppeis/closure-compiler-es6-compat-table

**Pull request merged**
