### PR TITLE
Change the default result class to "unknown"

### PR DESCRIPTION
**Pull request by afmenez**
Currently, if a test result is not specified for a given browser, it's assumed to be "false" (not supported).  I believe it would be more appropriate to default to "null" (support unknown) instead.
This fixes issue #1123 .

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
👍 I'll check this later today

**Comment by afmenez** [comment]
~~This changes the results for a lot of browsers.  I am preparing separate patches explicitly setting "false" to all the browsers I have tested (firefox 2-56, IE11, Edge 14-16, Opera 10-12).~~ This one was merged by itself with #1143

**Comment by afmenez** [comment]
I have added the explicit falses for IE11 on the non-standard table, but I can't check the other tabs due to #1127

**Comment by afmenez** [comment]
The explicit falses for Opera are already on #1129 , I will not repeat the changes here.

**Comment by afmenez** [comment]
~~For some reason, the undefined results for STAGE0 tests on esnext become green with the patch, when they should be gray.  I was not able to identify what is causing this.~~ (Fixed by #1192)

**Comment by afmenez** [comment]
This PR is more than 2 years old.  What is holding it back?

**Comment by chicoxyzzy** [comment]
Someone should check that everything looks fine in this branch. I think no one just did it yet =)

**Comment by nicolo-ribaudo** [comment]
This locally looks fine to me. I only have a comment, not directly caused by this PR but made more considerable.



Should the first row (the header) be gray rather than red?

**Comment by afmenez** [comment]
I agree with you, but I believe it is a separate issue...

**Review by nicolo-ribaudo — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Review by chicoxyzzy — APPROVED** [review]
Wow. That's a really barrel aged PR! Thank you for bearing with us @afmenez ❤️

**Pull request merged**
