### PR TITLE
Updating "obsolete:very" for Chrome & Firefox

### PR DESCRIPTION
**Pull request by afmenez**
Adding release dates for Chrome & Firefox, marking as "obsolete: very" the versions that became obsolete more than one year ago.

### CODE REVIEW

**Comment by afmenez** [comment]
Got Chrome dates from here:
https://en.wikipedia.org/wiki/Google_Chrome_version_history

And Firefox dates from here:
https://en.wikipedia.org/wiki/Firefox_version_history

**Comment by chicoxyzzy** [comment]
LGTM

**Comment by chicoxyzzy** [comment]
Maybe we should add release date to browser properties where possible? I think this info can be useful for projects like `babel-preset-env`, especially that `obsolete: very` doesn't really makes any sense for raw data. Not sure about property name and it's format. IMO format it should be human-readable and sortable `YYYY-MM-DD`. Thoughts?

**Comment by chicoxyzzy** [comment]
Actually we should use release dates too (instead of `obsolete: very`) to hide super old browsers in resulting HTML

**Comment by chicoxyzzy** [comment]
Please follow https://github.com/kangax/compat-table/issues/740#issuecomment-262230316

**Comment by afmenez** [comment]
My proposal is to add two new fields:

released: YYYY-MM-DD,
retired: YYYY-MM-DD

Then the build script would follow these rules:

- If "obsoleted:very" or retired>1 year old, don't show the browser;
- If "obsoleted:true" or retired is in the past, the browser is obsolete;
- If "unstable:true" or released is in the future, the browser is unstable;

I can do the first part (add the dates for Firefox and Chrome), but I need help with the second (changing the script).

**Comment by graingert** [comment]
@afmenez there's no reasonable definition of obsolete. Vendor supported or unsupported is something with a concrete definition.

> If "obsoleted:very" or retired>1 year old, don't show the browser;

each browser has different definitions on what they consider unsupported. compat-table shouldn't seek to define it for them with a specific time.

**Comment by afmenez** [comment]
@graingert , I believe you read my message too fast.  I never tried to define what obsolete is, I specifically included I field to define a date by browser.   The line you are commenting proposes a way to define when a browser is irrelevant and should not appear on the site anymore.  I proposed 1 year because it is similar to what is already on the data today, and is easy to script with the data already present (or proposed).

**Comment by ljharb** [comment]
Including date information is an excellent idea.

Programmatically using date information to determine obsoleteness is a very bad idea imo.

**Comment by chicoxyzzy** [comment]
@ljharb we can use date information not for obsoleteness but for what we call `obsolete: very`. Just to hide very old browsers in HTML (before we have some filters in UI)

**Comment by afmenez** [comment]
@ljharb , my proposal explicitly include a field for the date when the browser was declared obsolete (retired: YYYY-MM-DD), so we are not problematically determining anything.

**Comment by ljharb** [comment]
I don't think "very" applies based on time either, but rather based on what new versions have replaced it, or how technologically out of date.

@afmenez i think explicit dates for each status makes perfect sense. That would also enable us, on the ES5 tab, to have a different concept of "obsolete" than on the ES6 tab.

**Comment by afmenez** [comment]
Great, can I proceed with the fields I suggested?  I mean, I'll add the data now for informational purposes, and we can decide if/what to do with them later.

It would become like this:

```
  firefox31: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 31<br> ESR',
    released: 2014-07-22,
    retired: 2015-08-11,
    obsolete: very,
  }

  firefox45: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 45 ESR',
    released: 2016-03-08,
    retired: 2017-06-13,
    obsolete: false,
  },

  firefox52: {
    full: 'Firefox',
    family: 'SpiderMonkey',
    short: 'FF 52 Aurora',
    released: 2017-03-07,
    unstable: true,
    obsolete: false, // ESR (EOL on 2018)
  },
```

I would like to get some support because it is a lot of work, and I don't want to waste my time doing it and getting refused later.

**Comment by afmenez** [comment]
Maybe "release:" and "retire:" would be better, since we can have dates in the future.

**Comment by chicoxyzzy** [comment]
`release` and `retire` are OK IMO. Also I think we can change `build.js` later in another PR, after some further discussion in #740. So just adding new fields are enough for this PR

**Comment by afmenez** [comment]
Got IE dates from here:
https://en.wikipedia.org/wiki/Internet_Explorer_version_history#Release_history_for_desktop_Windows_OS_version

And Edge dates from here:
https://en.wikipedia.org/wiki/Microsoft_Edge#Release_history

**Comment by chicoxyzzy** [comment]
Can you please rebase? It should be as easy as taking my changes from `gh-pages` and re-run `build` task?

**Comment by chicoxyzzy** [comment]
I'm going to merge this now. Let's discuss what we mean by 'obsolete' and what should be obsolete and what not in #740

**Pull request merged**
