### PR TITLE
Fix mixed content issues

### LINKED ISSUE #249: Fix mixed content issues
Now would be a good time to switch to HTTPS. (No reason not to.)

https://kangax.github.io/compat-table/ currently has a few mixed content issues (see DevTools console).

### PR DESCRIPTION
**Pull request by mathiasbynens**
Fixes #249. This means that we can now use `https://kangax.github.io/compat-table/` (note the use of HTTPS) as the main URL without triggering errors.

### CODE REVIEW

**Comment by kangax** [comment]
Thanks @mathiasbynens!

**Comment by mathiasbynens** [comment]
You may need to update your Flattr settings accordingly.

**Comment by kangax** [comment]
Will do, thanks. Haven't checked it in ages...

**Comment by mathiasbynens** [comment]
Also this URL can/should be updated:

**Comment by kangax** [comment]
Updated

**Comment by mathiasbynens** [comment]
Hmm, I still see a URL without HTTPS there.

**Comment by kangax** [comment]
Oh, of course :) Updated again

**Pull request merged**
