### PR TITLE
feat(esnext): optional chaining and nullish coalescing operators to stage 3

### PR DESCRIPTION
**Pull request by Crow-EH**
Hello everybody !

[Optional chaining operator just reached stage 3.](https://github.com/tc39/proposal-optional-chaining/pull/107) 🎉

[Nullish coalescing operator reached stage 3 too.](https://github.com/tc39/proposal-nullish-coalescing/commit/c259ae18ebf5dd46deb7beffdc7249dde583c4bc) 🚀 

[The proposal table has already been updated for both.](https://github.com/tc39/proposals)

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Also nullish coalescing; could we update that too?

**Comment by Crow-EH** [comment]
Yes, I'll add it to this PR (and squash).

**Comment by Crow-EH** [comment]
It's done. Please tell me if I forgot something / made an error somewhere.

**Review by chicoxyzzy — APPROVED** [review]
Thank you!

**Pull request merged**
