### PR TITLE
[ES7] Add RegExp.escape

### PR DESCRIPTION
**Pull request by zloirock**
[Proposal](https://github.com/benjamingr/RexExp.escape), [result](https://githack.com/zloirock/compat-table/gh-pages/es7/index.html)

### CODE REVIEW

**Comment by kangax** [comment]
:+1:

**Comment by ljharb** [comment]
The proposal still hasn't been accepted as a [stage 0 proposal](https://github.com/tc39/ecma262/blob/master/stage0.md) - it's far too soon to have merged this into the compatibility table as "strawman". It should still be "pre-strawman".

**Comment by ljharb** [comment]
Let's please not be so hasty in the future with merging new proposals.

**Comment by kangax** [comment]
Oh, I forgot we have "pre-strawman", my bad.

**Comment by zloirock** [comment]
@ljharb I don't think this repo is last instance - by [criteria](https://docs.google.com/document/d/1QbEE0BsO4lvl7NFTn5WXWeiEIBfaVUF7Dk0hpPpPDzU/edit) it's already on stage 1.

**Comment by ljharb** [comment]
It may claim to be so, but the github repo is the source of truth. The criteria simply mean it's acceptable to _ask_ the committee to advance it - nothing automatically advances.

**Comment by zloirock** [comment]
IIRC most stage 0 strawmans from [this repo](https://github.com/tc39/ecma262/blob/master/stage0.md) not disussed in tc39 meetings.

**Pull request merged**
