### PR TITLE
Firefox 53 is being released today

### PR DESCRIPTION
**Pull request by afmenez**
Firefox 53 is being released today, I have updated its status.

Before anyone asks, [Mozilla is killing the "Aurora" version](http://release.mozilla.org/firefox/release/2017/04/17/Dawn-Project-FAQ.html), and this is already reflected in the patch.

### CODE REVIEW

**Comment by afmenez** [comment]
This release was postponed to tomorrow (apr/18), so this should not be merged until then.

**Comment by afmenez** [comment]
Firefox 53 is already live, but there's an issue in the es2016+ tab.  I'll fix it and update this PR in a moment.

**Comment by afmenez** [comment]
OK, patch updated to reflect the current features. I believe this is OK to merge.

**Comment by mgol** [comment]
@afmenez The Travis build has failed. It seems you forgot to rebuild the results?

**Comment by afmenez** [comment]
Well, I did did 2 rebuilds during the last rebase, but apparently it was not enough.  I believe it is OK now.

**Review by chicoxyzzy — APPROVED** [review]
LGTM

**Comment by afmenez** [comment]
Rebased again.  Wouldn't it be more fair to merge the oldest PRs first?

**Comment by chicoxyzzy** [comment]
@afmenez sorry about that. I just had seen PR which you also approved and wanted to merge it because I thought I won't have enough time to review other PRs. Later I've got some more free time for review

**Comment by ljharb** [comment]
For the record, I wouldn't say "oldest first"; usually I merge the simplest PRs first.

**Comment by mgol** [comment]
That's a problem with the current workflow - any change in the data modifies HTML files making all other PRs have merge conflicts. If someone asks people in multiple PRs to rebase & resolve conflicts, it's likely that one of them will have conflicts again very soon.

Perhaps it'd be better to have `master` as the main branch with a Travis hook that on new commits to `master` would regenerate `gh-pages` based on current commit with built HTML files? That would be way more friendly towards contributors.

**Comment by chicoxyzzy** [comment]
@mgol we discussed that before. We need @kangax' help for that. And likely a separate issue.

**Pull request merged**
