### PR TITLE
Update data for Duktape 2.7

### PR DESCRIPTION
**Pull request by omasanori**
Intentionally ignored these false-positives:

data-esintl -> Intl.Collator -> rejects invalid language tags
data-esintl -> NumberFormat -> accepts valid language tags
data-esintl -> DateTimeFormat -> rejects invalid language tags

Marked Duktape releases before 2020 as obsolete: very.

### CODE REVIEW

**Comment by ljharb** [comment]
Can you elaborate on the “false positives”?

**Comment by omasanori** [comment]
Thank you for your comment, @ljharb! As you can see at https://kangax.github.io/compat-table/esintl/, Duktape does not implement Collator, NumberFormat, and DateTimeFormat at all. Thus, these tests should be `false` but actually treated as `true`.

**Comment by ljharb** [comment]
That suggests the tests are wrong :-) would you be interested in a PR to fix them?

**Comment by omasanori** [comment]
Yes, I will try.

**Comment by omasanori** [comment]
https://github.com/kangax/compat-table/pull/1795 is my proposal.

**Comment by chicoxyzzy** [comment]
Unfortunately this one have conflicts now

**Comment by omasanori** [comment]
Sure I will fix it.

**Comment by omasanori** [comment]
Updated to the latest results.

**Review by chicoxyzzy — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Pull request merged**
