### PR TITLE
`position: sticky;` is supported correctly in Firefox since version 32

### LINKED ISSUE #1139: Sticky thead works only in Safari
The current implementation of the position:sticky workaround (on master.js) works only in Safari:
```
  if (thead.css('position') === "-webkit-sticky") {
    // Remove floatThead when native position:sticky is usable.
    // Currently, only Safari (which floatThead incidentally does not support),
    // and its -webkit-sticky prefix, works correctly with <thead>.
    $.fn.floatThead = function() { return this };
  }
```
It should check also for the actual "sticky" value, which is implemented on Edge 16 preview and will possibly be implemented in other browsers in the future.

### PR DESCRIPTION
**Pull request by ExE-Boss**
See the MDN article [on the CSS `position` property](https://developer.mozilla.org/docs/Web/CSS/position#Browser_compatibility) for details.

Fixes #1139

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Seems fine. Not sure why the block needed to move orderings tho.

**Comment by ExE-Boss** [comment]
> Not sure why the block needed to move orderings tho.

That’s needed because of the Chrome issue.

**Comment by afmenez** [comment]
I have tried this before on #1139.  Is the order change enough to work around the bugs on both Chrome and Firefox?

**Comment by ExE-Boss** [comment]
From my own testing, it works perfectly on Firefox 60 without any issues (although I didn’t try it without #1303).

**Review by chicoxyzzy — APPROVED** [review]

**Pull request merged**
