### PR TITLE
Mark Chrome 79 as stable

### PR DESCRIPTION
**Pull request by zloirock**

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by chicoxyzzy** [comment]
Chrome 79 stable is not released yet https://omahaproxy.appspot.com

**Comment by ljharb** [comment]
lol, guess this should be reverted then

**Comment by zloirock** [comment]
Yep, I don't know why @ljharb merged it too early. Anyway, it's not a problem since it will be released today. I don't think that any actions required.

**Comment by ljharb** [comment]
Fair, i assumed i could trust the PR title, and that a stable PR wouldn’t go up until it was actually stable. I’ll be more careful in the future

**Pull request merged**
