### PR TITLE
Firefox 100 released

### PR DESCRIPTION
**Pull request by afmenez**
Firefox 100 was released today.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Comment by zloirock** [comment]
(Note that even FF99+ `Array#includes` [no longer properly works on sparse arrays](https://github.com/zloirock/core-js/commit/66be5f0b673714bc7cc72a3b5e437fe277465973), see ES2016+ table.)

**Comment by afmenez** [comment]
I can fix the ES6 results in a separate patch, but I need this to be merged first to avoid the conflicts.

**Comment by ljharb** [comment]
Went ahead and put up #1805 for https://bugzilla.mozilla.org/show_bug.cgi?id=1767541 (which i just filed, since it seems that nothing was previously filed).

I'll land this as soon as it gets a second approval, and I'm happy to handle any merge conflicts.

**Review by chicoxyzzy — APPROVED** [review]
LGTM

**Pull request merged**
