### PR TITLE
Changed browser selection that hide other browsers

### LINKED ISSUE #457: Can you frozen the first column?
I want to one platform as iojs that's nearly the last one, I compare the feature with the scrollbar left-to-right. 

Or hide the others when I choose one platform.

### PR DESCRIPTION
**Pull request by popomore**
Only show one colunm when selected

https://popomore.github.io/compat-table/es6/#iojs

Closes #457

### CODE REVIEW

**Comment by webbedspace** [comment]
This doesn't work when I click an obsolete browser's column.

**Comment by popomore** [comment]
See that, I will figure it out soon.

**Comment by popomore** [comment]
Fix it.

Also fix selecting an obsolete browser. Example http://kangax.github.io/compat-table/es6/#firefox17

Known issue: the count of the colspan of category has not changed when column changed.

**Comment by kangax** [comment]
I like the idea, but the implementation could use some tweaking. On my wide screen, horizontally-huge cells look bad. They also don't scale well when I resize it down (or on tablets, mobile, etc. I imagine). It's also not clear to someone unfamiliar with the UI that clicking somewhere else will bring other columns back.

**Comment by popomore** [comment]
How about add a compare button, platform can be chosen not only one, then change the hash like `#iojs+nodejs`.

The changed hash will trigger a new overlay show the result and given a return button.

**Comment by kangax** [comment]
I like it. But what do you mean by overlay? How would that look?

**Comment by popomore** [comment]
Maybe it's a `div` with large z-index cover the page.

**Comment by popomore** [comment]
Can I refactor it with browserify?

**Comment by kangax** [comment]
What exactly and why?

**Comment by webbedspace** [comment]
Closing this because of non-response, and because I believe sticky header solutions (like #532) are more useful.

**Pull request closed without merging**
