### PR TITLE
Add Array.prototype.contains to ES7 table.

### PR DESCRIPTION
**Pull request by ziyunfei**

### CODE REVIEW

**Comment by webbedspace** [comment]
Your result for FF35 is semantically incorrect: FF35 _is_ Nightly at present, so its support should be listed as `true`. Stable Firefox is FF32 and has no bearing on FF35's result.

**Comment by ziyunfei** [comment]
@webbedspace  Sorry for confusing you, "only enabled in Nightly builds" here means this method is only enabled in FF35 Nightly, FF36 Nightly, FF37 Nightly, etc... but not enabled in FF35 aurora or FF35 stable, until [bug 1070767](https://bugzilla.mozilla.org/show_bug.cgi?id=1070767) is resolved.

**Comment by webbedspace** [comment]
Eh? OK, fair enough.

**Comment by kangax** [comment]
Thanks!

**Comment by nunnly** [comment]
ES7 .....

**Pull request merged**
