### PR TITLE
Add 6to5 colmun

### PR DESCRIPTION
**Pull request by e-jigsaw**
For #281 .

I checked [this](https://github.com/e-jigsaw/6to5-es6-compat-table) inspired by [teppeis/closure-compiler-es6-compat-table](https://github.com/teppeis/closure-compiler-es6-compat-table).

But, some tests are maybe incorrect. For example `let`. Compiled code from `let` test raised error

```
[ReferenceError: __let_script_executed is not defined]
```

compiled code is

``` javascript
// let
"use strict";
module.exports = function() {

            try {
              return (function () { "use strict"; __let_script_executed = true; var _foobarbaz2 = 123; return _foobarbaz2 == 123; }());
            } catch (e) {
              return false;
            }

};
```

### CODE REVIEW

**Comment by webbedspace** [comment]
I'm not sure it's possible for a compiler to pass "`__proto__` in object literals" or the typed array tests on its own. (I'm aware the table currently lists Traceur as passing the former, but I feel that's an error, at least as compared to EJS and Closure).

**Comment by e-jigsaw** [comment]
@webbedspace Could you're right in "`__proto__` in object literals" case. Error raised where it was confirmed by the following code.

```
function test() {
  var passed = { __proto__ : [] } instanceof Array
    && !({ __proto__ : null } instanceof Object);

  // If computed properties are supported, the following
  // check must also be passed.
  var a = "__proto__";
  try {
    passed &= !({ [a] : [] } instanceof Array);
  }
  catch(e) {}
  return passed;
}

console.log(test());
// => 0
```

But, "typed arrays" case is passed following code:

```
function test() {
  var buffer = new ArrayBuffer(64);
  var passed = true;
  var view;

  // Check that each int type overflows as expected.
  view = new Int8Array(buffer);         view[0] = 0x80;
  passed &= view[0] === -0x80;
  view = new Uint8Array(buffer);        view[0] = 0x100;
  passed &= view[0] === 0;
  view = new Uint8ClampedArray(buffer); view[0] = 0x100;
  passed &= view[0] === 0xFF;
  view = new Int16Array(buffer);        view[0] = 0x8000;
  passed &= view[0] === -0x8000;
  view = new Uint16Array(buffer);       view[0] = 0x10000;
  passed &= view[0] === 0;
  view = new Int32Array(buffer);        view[0] = 0x80000000;
  passed &= view[0] === -0x80000000;
  view = new Uint32Array(buffer);       view[0] = 0x100000000;
  passed &= view[0] === 0;
  // Check that each float type loses precision as expected.
  view = new Float32Array(buffer);      view[0] = 0.1;
  passed &= view[0] === 0.10000000149011612;
  view = new Float64Array(buffer);      view[0] = 0.1;
  passed &= view[0] === 0.1;
  return passed;
}

console.log(test());
// => 1
```

I will fix it.

**Comment by webbedspace** [comment]
Question: which host JS environment are you running these in? Ideally the 6to5 output should be run in something confirmed to have close to zero native ES6 support (like IE10 - taking into account it does support DataView, String HTML and hoisted block functions by itself).

I ask because Typed Arrays refers to a low-level byte manipulation interface, which would not be very feasible for compiled JS code to emulate (and because 6to5's documentation makes no claim to this).

**Comment by e-jigsaw** [comment]
I checked by Node.js(`v0.10.32`)

**Comment by webbedspace** [comment]
That being so, I'd like to run all of the passing compiled code against IE 10 or IE 9 to confirm its actual efficacy.

**Comment by e-jigsaw** [comment]
Oh, add column is hard way... X(

**Comment by e-jigsaw** [comment]
@sebmck Is 6to5 supported IE 10 or IE9??

**Comment by sebmck** [comment]
@e-jigsaw It should. Nothing is output that wouldn't be supported AFAIK.

**Pull request closed without merging**
