### PR TITLE
Firefox 75 release

### PR DESCRIPTION
**Pull request by chicoxyzzy**
I've found no changes

### CODE REVIEW

**Review by ljharb — APPROVED** [review]
Is there anything that should be adjusted here based on #1598?

**Comment by chicoxyzzy** [comment]
Do we consider version as very obsolete when its release date is over a year or when its retire date was more than a year ago? I don't remember.

**Comment by ljharb** [comment]
I'd say retire date, to be safer.

**Comment by chicoxyzzy** [comment]
fixed :)

**Pull request merged**
