### PR TITLE
Fix Array.prototype[Symbol.unscopables] test

### PR DESCRIPTION
**Pull request by arv**
The unscobables of the Array.prototype is no longer an Array.

### CODE REVIEW

**Comment by arv** [comment]
Test now passes in Chrome 38

**Comment by webbedspace** [comment]
The client-side tests are actually supposed to be ES3-compliant outside of the tested feature (at the very least because the ES5 page is expected to run on not-fully-compliant browsers) so Array#every is (currently) frowned upon. Yes, I know the likelihood of a platform implementing Symbol.iterator but not the Array extras is remarkably low, but coupling these two unrelated features is still a bit improper. See #190.

(This is also why plain for-i loops and `instanceof Array` are used in several other tests instead of isArray and forEach).

**Comment by webbedspace** [comment]
(Astute viewers may have noticed that contrary to the above pronouncement, a previous test I contributed for Symbols does use several ES5 methods without checking for existence. I wish to make amends with #206.)

**Comment by arv** [comment]
Changed it to a plain ol for loop.

PTAL

**Comment by arv** [comment]
Updated data-es6.js and ran `node build.js`.

PTAL

**Comment by kangax** [comment]
Thanks!

**Pull request merged**
