### PR TITLE
Add results for Chrome 61 Canary

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Needs review because Shared memory could be enabled in my Canary build because of feature testing.

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
Also added commit ae77d64 here. Chrome 59 stable will be released tomorrow.

**Review by ljharb — APPROVED** [review]

**Review by afmenez — APPROVED** [review]
LGTM

**Comment by chicoxyzzy** [comment]
Thank you for review! I'll merge this after Chrome 59 release!

**Comment by afmenez** [comment]
Then you forgot to change Chrome 59 to stable...

**Comment by afmenez** [comment]
While we're at it, why do we keep adding an Opera reference on every Chrome release?  We don't do this for any other derivative browser (Iceweasel, Tor, and so on...).

**Review by afmenez — APPROVED** [review]
LGTM

**Pull request merged**
