### PR TITLE
Adds es6-shim support column

### PR DESCRIPTION
**Pull request by webbedspace**
es6-shim is grouped under the newly renamed "compilers/polyfills" platform category.

### CODE REVIEW

**Comment by Yaffle** [comment]
es6-shim is a part of "6to5 + polyfill", not?

**Comment by webbedspace** [comment]
No, 6to5's [polyfill](https://6to5.org/polyfill.html) instead uses [core.js](https://github.com/zloirock/core-js).

**Comment by Yaffle** [comment]
they switched to core.js 2 weeks ago, seems...

**Comment by webbedspace** [comment]
@kangax Merge conflict resolved.

**Pull request merged**
