### PR TITLE
Added Jscrambler to the compiler group

### PR DESCRIPTION
**Pull request by CMatias**

### CODE REVIEW

**Comment by ljharb** [comment]
What is jscrambler?

**Comment by zloirock** [comment]
IIRC it was obfuscator... I can understand the support of ES6 syntax, but it really also adds polyfills? And how implemented some features like `Symbol.unscopables`? I do not believe that the results are correct.

**Comment by zloirock** [comment]
95%, really?

**Comment by ljharb** [comment]
@CMatias can you provide some articles, links, and sources to justify why this is worth putting in the table?

**Comment by kangax** [comment]
Please, no. I would rather not add various "services" to the table, especially as ridiculous ones as JScrambler.

**Comment by ljharb** [comment]
Closing for now. Happy to review further justification materials - but since all of us either have no idea what it is, or don't think well of it, let's say no for now.

**Comment by pfortuna** [comment]
Hey guys. I'm Pedro from Jscrambler. We respect not wanting to add services to the table. That would be enough for us to pull out the PR. No need for the gratuitous puns :-) keep up the good work.

**Pull request closed without merging**
