### PR TITLE
Add Rhino 1.7.15

### PR DESCRIPTION
**Pull request by gausie**
- **Add new version environment**
- **Update instructions at the top of rhino.js**
- **Update newly passing tests for Rhino 1.7.15**
- **Fix some old tests that were erroneously marked as true, thus the new falses are not regressions**

### CODE REVIEW

**Review by chicoxyzzy — APPROVED** [review]
LGTM
Can you please rebase and regenerate HTML files?

**Comment by ljharb** [comment]
@chicoxyzzy ill take care of it :-) reminder that PRs still need two green checks before they can be landed.

**Comment by ljharb** [comment]
(also, the consecutive falses are necessary and desired; every version that a human has verified should have an entry in the data)

**Review by ljharb — APPROVED** [review]

**Comment by gausie** [comment]
Noted, thanks. Everywhere an old one was turned to false needs an extra
false added now then. I am ill at the moment so can get to it over the
weekend.

**Comment by ljharb** [comment]
sounds good, we'll fix that in a followup.

**Pull request merged**
