### PR TITLE
Adds STAGE4 on the ESNext tab

### PR DESCRIPTION
**Pull request by afmenez**
Adds STAGE4 on the ESNext tab, and moves "Hashbang Grammar" and "Array find from last" proposals there.

### CODE REVIEW

**Review by zloirock — COMMENTED** [review]
It should be added to `es2016plus` table to the new `2023 features` section.

**Review by ljharb — CHANGES_REQUESTED** [review]
as mentioned, stage 4 features go into their ES year, and don't need their own category.

**Comment by afmenez** [comment]
Yep, I tried to move to ES year first on #1821, but you said it was too soon...

**Comment by ljharb** [comment]
Right - it’s either stage 3, or it moves to stage 4 when it’s merged into the spec. We don’t need to ack proposals that are stage 4 but not yet merged.

**Pull request closed without merging**
