### PR TITLE
Partial results: extras

### PR DESCRIPTION
**Pull request by webbedspace**
This is an extra branch off of #280, and organises yet more existing tests into super- and sub-tests. I'm keeping this separate so that #280's changeset is easier to peruse and verify.
- Function "name" property (this has all of the tests added by #256, divided into sub-tests)
- Object static methods
- String.prototype methods
- Array static methods
- Array prototype methods
- Number properties
- `Object.prototype.__proto__`
- `__proto__` in literals (this also fixes some results for compilers)
- Generators (also adds a test for shorthand generator methods)

https://rawgit.com/webbedspace/compat-table/partial-extras/es6/index.html

### CODE REVIEW

**Comment by kangax** [comment]
@webbedspace I noticed code popup appearing somewhere way off to the bottom/right at times. Can you reproduce this as well?

**Comment by webbedspace** [comment]
I've just added some commits to close some test and result bugs. This now closes #239, #227 and #276.

**Comment by webbedspace** [comment]
@kangax This is a bug introduced in my earlier jQuery pullrequest. #287 is added to address it.

**Comment by kangax** [comment]
Other than this, I'm OK with pulling this in. And, again, huge thanks for taking care of all this!

**Comment by webbedspace** [comment]
OK, done.
(EDIT: Also rebased.)

**Comment by kangax** [comment]
Awesome, thanks!

**Pull request merged**
