### PR TITLE
Edge 79 release

### PR DESCRIPTION
**Pull request by chicoxyzzy**
https://blogs.windows.com/windowsexperience/2020/01/15/new-year-new-browser-the-new-microsoft-edge-is-out-of-preview-and-now-available-for-download/

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
I moved all Edge versions below Chrome to make `equals` field work

**Comment by ljharb** [comment]
Have you downloaded it and verified that it passes all the chrome 79 tests?

**Comment by chicoxyzzy** [comment]
@ljharb yep. Tested on macOS 10.15

**Review by ljharb — APPROVED** [review]

**Comment by mgol** [comment]
What's the reason to keep Chrome & Opera grouped & Edge 79+ separate when they are all based on Chromium?

**Comment by chicoxyzzy** [comment]
I also thought about that. Do you think it'll be better to group Edge also?

**Comment by mgol** [comment]
For me it makes sense to keep all Chromium browsers in one entry as long as none of them does modifications to the JS engine by itself and AFAIK that hasn't happened so far. Obviously, Edge 18 & older need to stay separate.

**Pull request merged**
