### PR TITLE
Edge 17 release

### PR DESCRIPTION
**Pull request by chicoxyzzy**
This PR just moves Edge 17 to stable and adds Edge 18. It doesn't add any new Edge 17/18 features to table, because I can't check them on my laptop

### CODE REVIEW

**Comment by mgol** [comment]
I've just checked the results on my laptop. The whole "shared memory and atomics" section is not supported by Edge 17 while it's shown as supported in the current data; it should be switched off.

The other sections look correct at first sight.

**Comment by chicoxyzzy** [comment]
@mgol thank you!

**Comment by chicoxyzzy** [comment]
I don't know why Travis fails. All tests pass on my machine and everything is up-to-date :/

**Comment by mgol** [comment]
It's in the Travis output:
```
No local changes to save
[ES5] Write to file es5/index.html
[ES6] Write to file es6/index.html
[ES2016+] Write to file es2016plus/index.html
[ES Next] Write to file esnext/index.html
Please run `npm run build` and commit the changes.
```
Your test results are out of date, it seems.

**Comment by chicoxyzzy** [comment]
Yes, I've seen this but I'm pretty sure they are up to date

**Comment by chicoxyzzy** [comment]
Didn't notice https://github.com/kangax/compat-table/pull/1290 was merged. Yep I should update my gh-pages branch

**Comment by afmenez** [comment]
I wrote a similar patch, only saw this as I was pushing it.  There were more changes on my patch:
- The SIMD extensions on the esnext tab are "false" since Edge16;
- As noted by @mgol , the shared memory extensions on the es2016+ tab are not supported anymore, as with the other major browsers.  As with the other browsers, I had a note explaining the problem;
- All of the flagged features on the es6 tab seem to be missing on this release.  I am not sure if the flag changed or what, but I couldn't make them work on Edge 17;
- There's no "Edge 18 Preview" yet, maybe it is too early to make the table bigger;
- I added obsolete:"very" to Edge 12 and 13, to make the table smaller;

I suggest you add these changes too.  Or I could push my patch instead.  Otherwise I'll rebase and push later.

**Comment by chicoxyzzy** [comment]
> There's no "Edge 18 Preview" yet, maybe it is too early to make the table bigger;

There is. https://github.com/Fyrd/caniuse/issues/4172

**Comment by chicoxyzzy** [comment]
> All of the flagged features on the es6 tab seem to be missing on this release. I am not sure if the flag changed or what, but I couldn't make them work on Edge 17;

@dstorey are this features removed from Edge 17?

@afmenez I think we can just merge this PR first, then apply your PR on top of it is it ok for you.

> I added obsolete:"very" to Edge 12 and 13, to make the table smaller;

I'm not sure that we want to make table smaller. We want it to provide useful information for developers. Let's see what others think.

**Review by zloirock — APPROVED** [review]

**Review by ljharb — APPROVED** [review]

**Pull request merged**
