### PR TITLE
Updating esnext and es2016+ results for Chrome 60

### PR DESCRIPTION
**Pull request by afmenez**
Addressing comments on PR #1196.  I don't have access to Chrome 60 to actually run the tests.

### CODE REVIEW

**Review by ljharb — APPROVED** [review]

**Review by mgol — CHANGES_REQUESTED** [review]
I've just loaded the tables in Chrome 60 with Experimental Javascript enabled on BrowserStack and these changes look correct. However, there's one more change - all tests pass in the 2016+ table with the flag on.

Could you change the result in "2017 annex b"'s entry "Object.prototype getter/setter methods" to be `flag` starting from Chrome 60, not 61?

The rest looks OK at first sight.

**Comment by afmenez** [comment]
es2016+ test results updated.

**Review by mgol — APPROVED** [review]

**Comment by afmenez** [comment]
Please merge this before the Chrome 62 patches to avoid the conflict.

**Review by chicoxyzzy — APPROVED** [review]

**Comment by afmenez** [comment]
Thanks!

**Pull request merged**
