### PR TITLE
Update WebKit to r195594

### PR DESCRIPTION
**Pull request by gskachkov**
- Arrow function: lexical "arguments" binding
- typed arrays: ArrayBuffer[Symbol.species]
- Map: Map[Symbol.species]
- Set: Set[Symbol.species]
- Promise: Promise[Symbol.species]
- well-known symbols: Symbol.species, existence
- RegExp.prototype properties: RegExp[Symbol.species]
- Array static methods: Array[Symbol.species]

### CODE REVIEW

**Comment by ljharb** [comment]
This may not be based on the latest master - mind rebasing and rerunning `npm run build`?

**Comment by gskachkov** [comment]
Ohh, OK. I'll do

**Comment by kangax** [comment]
You webkit folks are taking this whole ES6 thing seriously, I see... :D

**Comment by gskachkov** [comment]
@ljharb  Should be better now. 
@kangax Yeah, we are trying :-)

**Comment by ljharb** [comment]
@gskachkov looks good but would you mind rebasing this down to a single commit, specifically to remove the merge commit?

**Comment by gskachkov** [comment]
@ljharb Sorry. Fixed

**Pull request merged**
