### PR TITLE
Add new subtests for scope shadow resolution

### PR DESCRIPTION
**Pull request by afmenez**
This tries to address issue #1175.

Possible issues with this patch:
- I don't have a Mac to test, so I am not sure it actually fails on Safari. Can anyone test this?
- I have only tested on current Firefox, IE, Edge and Chrome, the other results are assumed to be the same as the block-scope tests.  Should they be changed to "null"?

### CODE REVIEW

**Comment by chicoxyzzy** [comment]
I'll try to check this PR tomorrow

**Comment by afmenez** [comment]
I am not sure this is needed anymore.  The original issue was about a problem on Safari 10 to 11, but now it seems the issue does not exist on Safari 10.1 and 11.  So it would only affect Safari 10, but we were not able to test it with that version.
I see 2 alternatives here:
- Change the Safari 10 result to `null`;
- We find someone that can test this on Safari 10.  If it passes, we can drop this patch, if it doesn't we add the `false` result;

**Comment by ljharb** [comment]
Let's wait on the latter option.

**Comment by afmenez** [comment]
Again I can't find what is the problem here.  I looked at the logs but could not find the cause of the error.  I have run `npm test` locally, and this is the output:
```
> compat-table@0.0.0 pretest C:\Users\alexandre.menezes\Documents\Kangax\compat-table
> npm run lint

> compat-table@0.0.0 lint C:\Users\alexandre.menezes\Documents\Kangax\compat-table
> jshint .

> compat-table@0.0.0 test C:\Users\alexandre.menezes\Documents\Kangax\compat-table
> echo 'Error: no test specified'

'Error: no test specified'
```
Any help will be appreciated.

**Review by chicoxyzzy — APPROVED** [review]
I had no chance to check results in Safari 10. I think we can merge this as it is after rebase

**Comment by afmenez** [comment]
Rebased.

**Pull request merged**
