### PR TITLE
[ES6] Update Chrome 52 results

### PR DESCRIPTION
**Pull request by chicoxyzzy**
Version 52.0.2723.0 canary (64-bit) now supports TCO without flags

### CODE REVIEW

**Comment by zloirock** [comment]
default

**Comment by chicoxyzzy** [comment]
I'm seeing 100% support starting from version 52.0.2721.0 as mentioned [here](https://twitter.com/chicoxyzzy/status/726937461377667073)

**Comment by chicoxyzzy** [comment]
I'm on OS X is it does makes any sense

**Comment by zloirock** [comment]
AFAIK they did not want to enable it because of https://github.com/tc39/proposal-ptc-syntax

cc @littledan

**Comment by chicoxyzzy** [comment]
Wow. Am I a/b tester? 😃

**Comment by littledan** [comment]
We are currently running an experiment on Canary and Dev channel usage of turning on ES2015 implicit tail calls, to assess the stability of the feature. We are not currently turning it on for any build beyond Canary and Dev. This should benefit the correctness of our implementation of tail call elimination in general, whether TC39 settles on explicit syntax for tail calls or not, and doesn't indicate an intention to ship tail calls beyond Canary.

For Kangax, probably this should read as red, with a little green flag, because it is currently on in Canary when "Experimental JavaScript features" is enabled. For more details on our position on tail calls, see [this V8 blog post](http://v8project.blogspot.com/2016/04/es6-es7-and-beyond.html).

**Comment by chicoxyzzy** [comment]
I've triple-checked that `Experimental JavaScript features` are disabled in my Canary but I'm still have tests pass for implicit TC as I mentioned in [this](https://github.com/kangax/compat-table/pull/790#issuecomment-216692463) comment

**Comment by chicoxyzzy** [comment]
52.0.2724.0 and it is 99% ES6 now (ಠ_ಠ)

**Comment by chicoxyzzy** [comment]
does it mean Canary automatically tests features in browsers and sends data to Google?

https://twitter.com/MHablich/status/727723055708049408

**Comment by ljharb** [comment]
it wouldn't be a canary if it didn't report failures early :-p

**Comment by natorion** [comment]
This whole PR gets a little bit offtopic and can be rejected because we are currently not shipping PTC.

And yes, features are tested on Canary, that is the point of it. We only get anomized data if you opt-in though.

**Pull request closed without merging**
